sources:
  - name: tap_yfinance_dev
    schema: tap_yfinance_dev
    database: financial_elt
    loaded_at_field: _sdc_batched_at
    freshness:
      error_after:
        count: 1
        period: day
    tables:
      - name: stock_prices_1m
      - name: stock_prices_2m
      - name: stock_prices_5m
      - name: stock_prices_1h
      - name: stock_prices_1d
      - name: forex_prices_1m
      - name: forex_prices_2m
      - name: forex_prices_5m
      - name: forex_prices_1h
      - name: forex_prices_1d
      - name: crypto_prices_1m
      - name: crypto_prices_2m
      - name: crypto_prices_5m
      - name: crypto_prices_1h
      - name: crypto_prices_1d
      - name: actions
      - name: balance_sheet

models:
  - name: yf_stock_prices_1d
    description: "Yahoo finance stock prices deduped by day and ticker"
    config:
      contract:
        enforced: true
    constraints:
      - type: primary_key
        columns:
          - timestamp
          - ticker
    columns:
      - name: ticker
        data_type: text
        constraints:
          - type:
              not_null
      - name: timestamp
        data_type: timestamp
        constraints:
          - type: not_null
      - name: timestamp_tz_aware
        data_type: text
      - name: timezone
        data_type: text
      - name: open
        data_type: decimal(18, 2)
      - name: high
        data_type: decimal(18, 2)
      - name: low
        data_type: decimal(18, 2)
      - name: close
        data_type: decimal(18, 2)
      - name: volume
        data_type: decimal(18, 2)
      - name: dividends
        data_type: decimal(18, 2)
      - name: stock_splits
        data_type: decimal(18, 2)
      - name: repaired
        data_type: boolean
      - name: replication_key
        data_type: text
