- financial_elt:
  - yfinance_elt: true
    yfinance_elt_cron: "{'year': '*', 'month': '*', 'day': '*', 'week': '*', 'day_of_week': '3', 'hour': '0', 'minute': '00', 'second': '0'}"
  - feature_creation: false
  - alpha_vantage: false

- numerai:
  - numerai_tournament: false
  - numerai_signals: false

- dashboards:
  - dash: false