filebeat.inputs:
- type: filestream
  id: container-logs-filestream
  enabled: true
  paths:
    - /var/lib/docker/containers/*/*.log

  json.enabled: true
  json.keys_under_root: true
  json.add_error_key: true

  processors:
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"

  - decode_json_fields:
      when.has_fields: ['message']
      fields: ['message']
      target: 'docker'
      overwrite_keys: true

filebeat.config.modules:
  path: /nonexistent/modules.d/*.yml
  reload.enabled: false


# =============================== Outputs ===============================

output.elasticsearch:
  # connect to the 'elasticsearch' service name within the Docker network
  hosts: ["elasticsearch:9200"]
    # TODO: add auth for production
  # username: "elastic"
  # password: <"pwd">

  setup.template:
    enabled: true
    overwrite: true
