filebeat.inputs:
# Capture all .log files in /app/logs and subdirectories
- type: filestream
  id: app-logs
  enabled: true
  paths:
    - /app/logs/**/*.log
    - /app/logs/*.log
  processors:
    - rename:
        fields:
          - from: "log"
            to: "message"
        ignore_missing: true

# Capture only stdout/stderr from your app container
- type: container
  enabled: true
  paths:
    - /var/lib/docker/containers/*/*.log
  processors:
    - add_docker_metadata: ~
    - rename:
        fields:
          - from: "log"
            to: "message"
        ignore_missing: true

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]

setup.ilm.enabled: true
setup.ilm.policy_name: "filebeat-5d-policy"
setup.ilm.overwrite: true
setup.ilm.policy_file: "/usr/share/filebeat/filebeat-5d-policy.json"

setup.kibana:
  host: "http://kibana:5601"

logging.level: info
