filebeat.inputs:
- type: filestream
  id: container-logs-filestream
  enabled: true
  paths:
    - /var/lib/docker/containers/*/*.log

  json.enabled: true
  json.keys_under_root: true
  json.add_error_key: true

  processors:
    # Remove ANSI color codes and trailing newlines from the 'log' field
    - script:
        lang: javascript
        id: strip-ansi
        source: >
          function process(event) {
            var log = event.Get("log");
            if (log) {
              // Strip ANSI color codes
              log = log.replace(/\u001b\[[0-9;]*m/g, "");
              // Remove trailing newlines and carriage returns
              log = log.replace(/[\r\n]+$/, "");
              event.Put("log", log);
            }
          }
    # Rename 'log' to 'message' for better visibility in Kibana
    - rename:
        fields:
          - from: "log"
            to: "message"
        ignore_missing: true

    # Add Docker metadata for container context
    - add_docker_metadata:
        host: "unix:///var/run/docker.sock"

    - decode_json_fields:
        when.has_fields: [ 'message' ]
        fields: [ 'message' ]
        target: 'docker'
        overwrite_keys: true

filebeat.config.modules:
  path: /nonexistent/modules.d/*.yml
  reload.enabled: false

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]

  # TODO: add auth for production
  # username: "elastic"
  # password: <"pwd">

  setup.template:
    enabled: true
    overwrite: true