networks:
  elastic: # shared network for all services
    driver: bridge # creates a bridge network named 'elastic' if it doesn't exist

volumes:
  elasticsearch_data:
  kibana_data:
  filebeat_data:

services:
  # --- Logging Infrastructure ---
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch
    platform: linux/amd64
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false # TODO: secure this for production
      # - ELASTIC_PASSWORD=<password>
    networks:
      - elastic
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
        # TODO: add resource limits
    env_file:
      - .env

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    container_name: kibana
    platform: linux/amd64
    environment:
      - ELASTICSEARCH_HOSTS=["http://elasticsearch:9200"]
      # - ELASTICSEARCH_PASSWORD=<pwd>
    networks:
      - elastic
    ports:
      - "5601:5601"
    volumes:
      - kibana_data:/usr/share/kibana/data
    depends_on:
      - elasticsearch
    env_file:
      - .env


  filebeat:
    image: docker.elastic.co/beats/filebeat:8.12.0
    user: root
    container_name: filebeat
    platform: linux/amd64
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro # mount the config file
      - /var/lib/docker/containers:/var/lib/docker/containers:ro # mount Docker log directory
      - /var/run/docker.sock:/var/run/docker.sock:ro # mount docker socket for metadata processor
      - ./projects/financial_elt/:/app_logs:ro
    networks:
      - elastic
    depends_on:
      - elasticsearch


  # --- Application Services ---
  financial_elt:
    build:
      context: ./projects/financial_elt/
      dockerfile: Dockerfile
      args:
        CI: "true"
    container_name: financial_elt
    platform: linux/amd64
    networks:
      - elastic
    volumes:
      # mount project code for dev
      - ./projects/financial_elt/:/app/
    env_file:
      - .env

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
