networks:
  elastic:
    driver: bridge

volumes:
  elasticsearch_data:
  kibana_data:
  filebeat_data:
  logs:  # Shared log volume

services:
  elasticsearch-${ENVIRONMENT}:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch-${ENVIRONMENT}
    platform: linux/amd64
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false # TODO: add pw for security purposes
      # - ELASTIC_PASSWORD=<password>

    networks:
      - elastic
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    env_file:
      - .env

  kibana-${ENVIRONMENT}:
    image: docker.elastic.co/kibana/kibana:8.13.4
    container_name: kibana-${ENVIRONMENT}
    platform: linux/amd64
    environment:
      - ELASTICSEARCH_HOSTS=["http://elasticsearch-${ENVIRONMENT}:9200"]
    networks:
      - elastic
    ports:
      - "5601:5601"
    volumes:
      - kibana_data:/usr/share/kibana/data
    depends_on:
      - elasticsearch-${ENVIRONMENT}
    env_file:
      - .env

  filebeat-${ENVIRONMENT}:
    image: docker.elastic.co/beats/filebeat:8.12.0
    user: root
    container_name: filebeat-${ENVIRONMENT}
    platform: linux/amd64
    networks:
      - elastic
    depends_on:
      - elasticsearch-${ENVIRONMENT}
    volumes:
      - filebeat_data:/usr/share/filebeat/data
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - logs:/app/logs:ro  # Shared log volume for app logs
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./filebeat/filebeat-5d-policy.json:/usr/share/filebeat/filebeat-5d-policy.json:ro
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch-{ENVIRONMENT}:9200

  financial-elt-${ENVIRONMENT}:
    build:
      context: ./projects/financial-elt/
      dockerfile: Dockerfile
      args:
        CI: "true"
    container_name: financial-elt-${ENVIRONMENT}
    platform: linux/amd64
    networks:
      - elastic
    env_file:
      - .env
    volumes:
      - logs:/app/logs  # App writes logs here
      - ./projects/financial-elt/tap-polygon/output:/app/tap-polygon/output
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    # increase ulimits to prevent deadlocks
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
