version: 1
disable_existing_loggers: false

formatters:
  json:
    (): meltano.core.logging.json_formatter
    callsite_parameters: true  # include file, line number, and function name

handlers:
  console_json:
    class: logging.StreamHandler
    level: INFO
    formatter: json
    stream: "ext://sys.stderr"

  file_json:
    class: logging.FileHandler
    level: INFO
    formatter: json
    filename: "meltano.log"
    mode: "a"
    encoding: "utf-8"

root:
  level: INFO
  handlers: [console_json, file_json]  # direct output from both files
