version: 1
send_anonymous_usage_stats: false
project_id: ${GCP_PROJECT_ID}

default_environment: dev

state_backend:
  type: remote
  uri: ${GCP_BUCKET_URI}
  gcs:
    application_credentials: ${GOOGLE_APPLICATION_CREDENTIALS}

environments:
  - name: dev
    config:
      plugins:
        loaders:
          - name: target-snowflake
            env:
              TARGET_SNOWFLAKE_DEFAULT_TARGET_SCHEMA: TAP_YFINANCE_DEV

  - name: production
    config:
      plugins:
        loaders:
          - name: target-snowflake
            env:
              TARGET_SNOWFLAKE_DEFAULT_TARGET_SCHEMA: TAP_YFINANCE_PRODUCTION

plugins:
  extractors:
    - name: "tap-yfinance"
      namespace: "tap_yfinance"
      pip_url: git+https://github.com/melgazar9/tap-yfinance@9f34b8e054be95ddafc6ee1e28a367f78109ff26

      capabilities:
        - state
        - catalog
        - discover
        - about
        - stream-maps

      select:
        - stock_tickers
        - futures_tickers
        - forex_tickers
        - crypto_tickers
        - stock_prices_1m
        - futures_prices_1m
        - forex_prices_1m
        - crypto_prices_1m
        - stock_prices_2m
        - futures_prices_2m
        - forex_prices_2m
        - crypto_prices_2m
        - stock_prices_5m
        - futures_prices_5m
        - forex_prices_5m
        - crypto_prices_5m
        - stock_prices_1h
        - futures_prices_1h
        - forex_prices_1h
        - crypto_prices_1h
        - stock_prices_1d
        - futures_prices_1d
        - forex_prices_1d
        - crypto_prices_1d
        - actions
        - balance_sheet
        - calendar
        - cash_flow
        - dividends
        - earnings_dates
        - fast_info
        - financials
        - history_metadata
        - income_stmt
        - insider_purchases
        - insider_roster_holders
        - insider_transactions
        - institutional_holders
        - major_holders
        - mutualfund_holders
        - news
        - shares_full
        - splits
        - option_chain
        - options
        - quarterly_balance_sheet
        - quarterly_cash_flow
        - quarterly_financials
        - quarterly_income_stmt
        - upgrades_downgrades

      config:
        default_start_date: "1950-01-01"
        add_record_metadata: true
        financial_category:

          ### tickers ###

          tickers:
            stock_tickers:
              tickers: '*'
              schema_category: stock_tickers
            futures_tickers:
              tickers: '*'
              schema_category: futures_tickers
            forex_tickers:
              tickers: '*'
              schema_category: forex_tickers
            crypto_tickers:
              tickers: '*'
              schema_category: crypto_tickers

          ### prices ###

          prices:
            stock_prices_1m:
              tickers: "*"
              yf_params: { "interval": 1m, "prepost": true, "repair": true, "auto_adjust": true, "back_adjust": false }
              schema_category: stock_prices

            futures_prices_1m:
              tickers: "*"
              yf_params: { "interval": 1m, "prepost": true, "repair": true, "auto_adjust": true, "back_adjust": false }
              schema_category: futures_prices

            forex_prices_1m:
              tickers: "*"
              yf_params: { "interval": 1m, "prepost": true, "repair": true, "auto_adjust": true, "back_adjust": false }
              schema_category: forex_prices

            crypto_prices_1m:
              tickers: "*"
              yf_params: { "interval": 1m, "prepost": true, "repair": true, "auto_adjust": true, "back_adjust": false }
              schema_category: crypto_prices


            stock_prices_2m:
              tickers: "*"
              yf_params: { "interval": 2m, "prepost": true, "repair": true, "auto_adjust": true, "back_adjust": false }
              schema_category: stock_prices

            futures_prices_2m:
              tickers: "*"
              yf_params: { "interval": 2m, "prepost": true, "repair": true, "auto_adjust": true, "back_adjust": false }
              schema_category: futures_prices

            forex_prices_2m:
              tickers: "*"
              yf_params: { "interval": 2m, "prepost": true, "repair": true, "auto_adjust": true, "back_adjust": false }
              schema_category: forex_prices

            crypto_prices_2m:
              tickers: "*"
              yf_params: { "interval": 2m, "prepost": true, "repair": true, "auto_adjust": true, "back_adjust": false }
              schema_category: crypto_prices


            stock_prices_5m:
              tickers: "*"
              yf_params: { "interval": 5m, "prepost": true, "repair": true, "auto_adjust": true, "back_adjust": false }
              schema_category: stock_prices

            futures_prices_5m:
              tickers: "*"
              yf_params: { "interval": 5m, "prepost": true, "repair": true, "auto_adjust": true, "back_adjust": false }
              schema_category: futures_prices

            forex_prices_5m:
              tickers: "*"
              yf_params: { "interval": 5m, "prepost": true, "repair": true, "auto_adjust": true, "back_adjust": false }
              schema_category: forex_prices

            crypto_prices_5m:
              tickers: "*"
              yf_params: { "interval": 5m, "prepost": true, "repair": true, "auto_adjust": true, "back_adjust": false }
              schema_category: crypto_prices


            stock_prices_1h:
              tickers: "*"
              yf_params: { "interval": 1h, "prepost": true, "repair": true, "auto_adjust": true, "back_adjust": false }
              schema_category: stock_prices

            futures_prices_1h:
              tickers: "*"
              yf_params: { "interval": 1h, "prepost": true, "repair": true, "auto_adjust": true, "back_adjust": false }
              schema_category: futures_prices

            forex_prices_1h:
              tickers: "*"
              yf_params: { "interval": 1h, "prepost": true, "repair": true, "auto_adjust": true, "back_adjust": false }
              schema_category: forex_prices

            crypto_prices_1h:
              tickers: "*"
              yf_params: { "interval": 1h, "prepost": true, "repair": true, "auto_adjust": true, "back_adjust": false }
              schema_category: crypto_prices


            stock_prices_1d:
              tickers: "*"
              yf_params: { "interval": 1d, "prepost": true, "repair": true, "auto_adjust": true, "back_adjust": false }
              schema_category: stock_prices

            futures_prices_1d:
              tickers: "*"
              yf_params: { "interval": 1d, "prepost": true, "repair": true, "auto_adjust": true, "back_adjust": false }
              schema_category: futures_prices

            forex_prices_1d:
              tickers: "*"
              yf_params: { "interval": 1d, "prepost": true, "repair": true, "auto_adjust": true, "back_adjust": false }
              schema_category: forex_prices

            crypto_prices_1d:
              tickers: "*"
              yf_params: { "interval": 1d, "prepost": true, "repair": true, "auto_adjust": true, "back_adjust": false }
              schema_category: crypto_prices

          ### financials ###

          financials:
            actions:
              tickers: "*"
              schema_category: get_actions

            balance_sheet:
              tickers: "*"
              schema_category: get_balance_sheet

            calendar:
              tickers: "*"
              schema_category: get_calendar

            cash_flow:
              tickers: "*"
              schema_category: get_cash_flow

            dividends:
              tickers: "*"
              schema_category: get_dividends

            earnings_dates:
              tickers: "*"
              schema_category: get_earnings_dates

            fast_info:
              tickers: "*"
              schema_category: get_fast_info

            financials:
              tickers: "*"
              schema_category: get_financials

            history_metadata:
              tickers: "*"
              schema_category: get_history_metadata

            income_stmt:
              tickers: "*"
              schema_category: get_income_stmt

            insider_purchases:
              tickers: "*"
              schema_category: get_insider_purchases

            insider_roster_holders:
              tickers: "*"
              schema_category: get_insider_roster_holders

            insider_transactions:
              tickers: "*"
              schema_category: get_insider_transactions

            institutional_holders:
              tickers: "*"
              schema_category: get_institutional_holders

            major_holders:
              tickers: "*"
              schema_category: get_major_holders

            mutualfund_holders:
              tickers: "*"
              schema_category: get_mutualfund_holders

            news:
              tickers: "*"
              schema_category: get_news

            shares_full:
              tickers: "*"
              schema_category: get_shares_full

            splits:
              tickers: "*"
              schema_category: get_splits

            option_chain:
              tickers: "*"
              schema_category: option_chain

            options:
              tickers: "*"
              schema_category: options

            quarterly_balance_sheet:
              tickers: "*"
              schema_category: quarterly_balance_sheet

            quarterly_cash_flow:
              tickers: "*"
              schema_category: quarterly_cash_flow

            quarterly_financials:
              tickers: "*"
              schema_category: quarterly_financials

            quarterly_income_stmt:
              tickers: "*"
              schema_category: quarterly_income_stmt

            upgrades_downgrades:
              tickers: "*"
              schema_category: get_upgrades_downgrades


      metadata:

        ### tickers ###

        stock_tickers:
          replication-method: INCREMENTAL
          replication-key: ticker
        futures_tickers:
          replication-method: INCREMENTAL
          replication-key: ticker
        forex_tickers:
          replication-method: INCREMENTAL
          replication-key: ticker
        crypto_tickers:
          replication-method: INCREMENTAL
          replication-key: ticker

        ### prices ###

        stock_prices_1m:
          replication-method: INCREMENTAL
          replication-key: timestamp
        futures_prices_1m:
          replication-method: INCREMENTAL
          replication-key: timestamp
        forex_prices_1m:
          replication-method: INCREMENTAL
          replication-key: timestamp
        crypto_prices_1m:
          replication-method: INCREMENTAL
          replication-key: timestamp

        stock_prices_2m:
          replication-method: INCREMENTAL
          replication-key: timestamp
        futures_prices_2m:
          replication-method: INCREMENTAL
          replication-key: timestamp
        forex_prices_2m:
          replication-method: INCREMENTAL
          replication-key: timestamp
        crypto_prices_2m:
          replication-method: INCREMENTAL
          replication-key: timestamp

        stock_prices_5m:
          replication-method: INCREMENTAL
          replication-key: timestamp
        futures_prices_5m:
          replication-method: INCREMENTAL
          replication-key: timestamp
        forex_prices_5m:
          replication-method: INCREMENTAL
          replication-key: timestamp
        crypto_prices_5m:
          replication-method: INCREMENTAL
          replication-key: timestamp

        stock_prices_1h:
          replication-method: INCREMENTAL
          replication-key: timestamp
        futures_prices_1h:
          replication-method: INCREMENTAL
          replication-key: timestamp
        forex_prices_1h:
          replication-method: INCREMENTAL
          replication-key: timestamp
        crypto_prices_1h:
          replication-method: INCREMENTAL
          replication-key: timestamp

        stock_prices_1d:
          replication-method: INCREMENTAL
          replication-key: timestamp
        futures_prices_1d:
          replication-method: INCREMENTAL
          replication-key: timestamp
        forex_prices_1d:
          replication-method: INCREMENTAL
          replication-key: timestamp
        crypto_prices_1d:
          replication-method: INCREMENTAL
          replication-key: timestamp


        ### financials ###

        actions:
          replication-method: INCREMENTAL
          replication-key: timestamp

        balance_sheet:
          replication-method: INCREMENTAL
          replication-key: date

        calendar:
          replication-method: INCREMENTAL
          replication-key: dividend_date

        cash_flow:
          replication-method: INCREMENTAL
          replication-key: date

        dividends:
          replication-method: INCREMENTAL
          replication-key: timestamp

        earnings_dates:
          replication-method: INCREMENTAL
          replication-key: timestamp

        fast_info:
          replication-method: INCREMENTAL
          replication-key: timestamp_extracted

        financials:
          replication-method: INCREMENTAL
          replication-key: date

        history_metadata:
          replication-method: INCREMENTAL
          replication-key: timestamp_extracted

        income_stmt:
          replication-method: INCREMENTAL
          replication-key: date

        insider_purchases:
          replication-method: INCREMENTAL
          replication-key: timestamp_extracted

        insider_roster_holders:
          replication-method: INCREMENTAL
          replication-key: latest_transaction_date

        insider_transactions:
          replication-method: INCREMENTAL
          replication-key: start_date

        institutional_holders:
          replication-method: INCREMENTAL
          replication-key: date_reported

        major_holders:
          replication-method: INCREMENTAL
          replication-key: timestamp_extracted

        mutualfund_holders:
          replication-method: INCREMENTAL
          replication-key: date_reported

        news:
          replication-method: INCREMENTAL
          replication-key: timestamp_extracted

        shares_full:
          replication-method: INCREMENTAL
          replication-key: timestamp

        splits:
          replication-method: INCREMENTAL
          replication-key: timestamp

        option_chain:
          replication-method: INCREMENTAL
          replication-key: last_trade_date

        options:
          replication-method: INCREMENTAL
          replication-key: timestamp_extracted

        quarterly_balance_sheet:
          replication-method: INCREMENTAL
          replication-key: date

        quarterly_cash_flow:
          replication-method: INCREMENTAL
          replication-key: date

        quarterly_financials:
          replication-method: INCREMENTAL
          replication-key: date

        quarterly_income_stmt:
          replication-method: INCREMENTAL
          replication-key: date

        upgrades_downgrades:
          replication-method: INCREMENTAL
          replication-key: grade_date

  loaders:
    - name: target-jsonl
      variant: andyh1203
      pip_url: target-jsonl

    - name: target-bigquery
      variant: z3z1ma
      pip_url: git+https://github.com/z3z1ma/target-bigquery.git@2d59eae0aa4a5468ed8ba5d04e8d239e05e373ee
      config:
        method: ${TARGET_BIGQUERY_METHOD}
        project: ${GCP_PROJECT_ID}
        credentials_path: ${GOOGLE_APPLICATION_CREDENTIALS}
        dataset: ${GCP_DATASET}
        batch_size: ${TARGET_BIGQUERY_BATCH_SIZE}
        denormalized: true
        bucket: ${GCP_BUCKET_NAME}
