version: 1
send_anonymous_usage_stats: false
project_id: ${GCP_PROJECT_ID}

default_environment: dev

state_backend:
  type: remote
  uri: ${GCP_BUCKET_URI}
  gcs:
    application_credentials: ${GOOGLE_APPLICATION_CREDENTIALS}

environments:
  - name: dev
    config:
      plugins:
        loaders:
          - name: target-snowflake
            env:
              TARGET_SNOWFLAKE_DEFAULT_TARGET_SCHEMA: TAP_YFINANCE_DEV

  - name: production
    config:
      plugins:
        loaders:
          - name: target-snowflake
            env:
              TARGET_SNOWFLAKE_DEFAULT_TARGET_SCHEMA: TAP_YFINANCE_PRODUCTION

plugins:
  extractors:
    - name: "tap-yfinance"
      namespace: "tap_yfinance"
      pip_url: git+https://github.com/melgazar9/tap-yfinance@395e43d56eff5308ffb4cd3e338a25fe264973d5

      capabilities:
        - state
        - catalog
        - discover
        - about
        - stream-maps

      select:
        - stock_tickers.*
        - futures_tickers.*
        - forex_tickers.*
        - crypto_tickers.*
        - crypto_tickers_top_250.*
        - stock_prices_1m.*
        - futures_prices_1m.*
        - forex_prices_1m.*
        - crypto_prices_1m.*
        - stock_prices_2m.*
        - futures_prices_2m.*
        - forex_prices_2m.*
        - crypto_prices_2m.*
        - stock_prices_5m.*
        - futures_prices_5m.*
        - forex_prices_5m.*
        - crypto_prices_5m.*
        - stock_prices_1h.*
        - futures_prices_1h.*
        - forex_prices_1h.*
        - crypto_prices_1h.*
        - stock_prices_1d.*
        - futures_prices_1d.*
        - forex_prices_1d.*
        - crypto_prices_1d.*
        - actions.*
        - balance_sheet.*
        - calendar.*
        - cash_flow.*
        - dividends.*
        - earnings_dates.*
        - fast_info.*
        - financials.*
        - history_metadata.*
        - income_stmt.*
        - insider_purchases.*
        - insider_roster_holders.*
        - insider_transactions.*
        - institutional_holders.*
        - major_holders.*
        - mutualfund_holders.*
        - news.*
        - recommendations.*
        - shares_full.*
        - splits.*
        - option_chain.*
        - options.*
        - quarterly_balance_sheet.*
        - quarterly_cash_flow.*
        - quarterly_financials.*
        - quarterly_income_stmt.*
        - upgrades_downgrades.*

      config:
        default_start_date: "1950-01-01"
        add_record_metadata: true

        ### tickers ###

        stock_tickers:
          tickers: '*'
        futures_tickers:
          tickers: '*'
        forex_tickers:
          tickers: '*'
        crypto_tickers:
          tickers: '*'
        crypto_tickers_top_250:
          tickers: '*'

        ### prices ###

        stock_prices_1m:
          tickers: "*"
          yf_params: { "interval": 1m, "prepost": true, "repair": true, "auto_adjust": true, "back_adjust": false }

        futures_prices_1m:
          tickers: "*"
          yf_params: { "interval": 1m, "prepost": true, "repair": true, "auto_adjust": true, "back_adjust": false }

        forex_prices_1m:
          tickers: "*"
          yf_params: { "interval": 1m, "prepost": true, "repair": true, "auto_adjust": true, "back_adjust": false }

        crypto_prices_1m:
          tickers: "*"
          yf_params: { "interval": 1m, "prepost": true, "repair": true, "auto_adjust": true, "back_adjust": false }


        stock_prices_2m:
          tickers: "*"
          yf_params: { "interval": 2m, "prepost": true, "repair": true, "auto_adjust": true, "back_adjust": false }

        futures_prices_2m:
          tickers: "*"
          yf_params: { "interval": 2m, "prepost": true, "repair": true, "auto_adjust": true, "back_adjust": false }

        forex_prices_2m:
          tickers: "*"
          yf_params: { "interval": 2m, "prepost": true, "repair": true, "auto_adjust": true, "back_adjust": false }

        crypto_prices_2m:
          tickers: "*"
          yf_params: { "interval": 2m, "prepost": true, "repair": true, "auto_adjust": true, "back_adjust": false }


        stock_prices_5m:
          tickers: "*"
          yf_params: { "interval": 5m, "prepost": true, "repair": true, "auto_adjust": true, "back_adjust": false }

        futures_prices_5m:
          tickers: "*"
          yf_params: { "interval": 5m, "prepost": true, "repair": true, "auto_adjust": true, "back_adjust": false }

        forex_prices_5m:
          tickers: "*"
          yf_params: { "interval": 5m, "prepost": true, "repair": true, "auto_adjust": true, "back_adjust": false }

        crypto_prices_5m:
          tickers: "*"
          yf_params: { "interval": 5m, "prepost": true, "repair": true, "auto_adjust": true, "back_adjust": false }


        stock_prices_1h:
          tickers: "*"
          yf_params: { "interval": 1h, "prepost": true, "repair": true, "auto_adjust": true, "back_adjust": false }

        futures_prices_1h:
          tickers: "*"
          yf_params: { "interval": 1h, "prepost": true, "repair": true, "auto_adjust": true, "back_adjust": false }

        forex_prices_1h:
          tickers: "*"
          yf_params: { "interval": 1h, "prepost": true, "repair": true, "auto_adjust": true, "back_adjust": false }

        crypto_prices_1h:
          tickers: "*"
          yf_params: { "interval": 1h, "prepost": true, "repair": true, "auto_adjust": true, "back_adjust": false }


        stock_prices_1d:
          tickers: "*"
          yf_params: { "interval": 1d, "prepost": true, "repair": true, "auto_adjust": true, "back_adjust": false }

        futures_prices_1d:
          tickers: "*"
          yf_params: { "interval": 1d, "prepost": true, "repair": true, "auto_adjust": true, "back_adjust": false }

        forex_prices_1d:
          tickers: "*"
          yf_params: { "interval": 1d, "prepost": true, "repair": true, "auto_adjust": true, "back_adjust": false }

        crypto_prices_1d:
          tickers: "*"
          yf_params: { "interval": 1d, "prepost": true, "repair": true, "auto_adjust": true, "back_adjust": false }

        ### wide ###
  
        stock_prices_wide_1m:
          tickers: "*"
          yf_params: { "interval": 1m, "prepost": true, "repair": true, "auto_adjust": true, "back_adjust": false }

        futures_prices_wide_1m:
          tickers: [ "ES=F", "CL=F" ]
          yf_params: { "interval": 1m, "prepost": true, "repair": true, "auto_adjust": true, "back_adjust": false }

        forex_prices_wide_1m:
          tickers: [ "EURUSD=X", "RUB=X" ]
          yf_params: { "interval": 1m, "prepost": true, "repair": true, "auto_adjust": true, "back_adjust": false }

        crypto_prices_wide_1m:
          tickers: [ "BTC-USD", "ETH-USD" ]
          yf_params: { "interval": 1m, "prepost": true, "repair": true, "auto_adjust": true, "back_adjust": false }

        ### financials ###

        actions:
          tickers: "*"

        balance_sheet:
          tickers: "*"

        calendar:
          tickers: "*"

        cash_flow:
          tickers: "*"

        dividends:
          tickers: "*"

        earnings_dates:
          tickers: "*"

        fast_info:
          tickers: "*"

        financials:
          tickers: "*"

        history_metadata:
          tickers: "*"

        income_stmt:
          tickers: "*"

        insider_purchases:
          tickers: "*"

        insider_roster_holders:
          tickers: "*"

        insider_transactions:
          tickers: "*"

        institutional_holders:
          tickers: "*"

        major_holders:
          tickers: "*"

        mutualfund_holders:
          tickers: "*"

        news:
          tickers: "*"

        recommendations:
          tickers: "*"

        shares_full:
          tickers: "*"

        splits:
          tickers: "*"

        option_chain:
          tickers: "*"

        options:
          tickers: "*"

        quarterly_balance_sheet:
          tickers: "*"

        quarterly_cash_flow:
          tickers: "*"

        quarterly_financials:
          tickers: "*"

        quarterly_income_stmt:
          tickers: "*"

        upgrades_downgrades:
          tickers: "*"


      metadata:

        ### tickers ###

        stock_tickers:
          replication-method: INCREMENTAL
          replication-key: ticker
        futures_tickers:
          replication-method: INCREMENTAL
          replication-key: ticker
        forex_tickers:
          replication-method: INCREMENTAL
          replication-key: ticker
        crypto_tickers:
          replication-method: INCREMENTAL
          replication-key: ticker
        crypto_tickers_top_250:
          replication-method: INCREMENTAL
          replication-key: ticker


        ### prices ###

        stock_prices_1m:
          replication-method: INCREMENTAL
          replication-key: timestamp
        futures_prices_1m:
          replication-method: INCREMENTAL
          replication-key: timestamp
        forex_prices_1m:
          replication-method: INCREMENTAL
          replication-key: timestamp
        crypto_prices_1m:
          replication-method: INCREMENTAL
          replication-key: timestamp

        stock_prices_2m:
          replication-method: INCREMENTAL
          replication-key: timestamp
        futures_prices_2m:
          replication-method: INCREMENTAL
          replication-key: timestamp
        forex_prices_2m:
          replication-method: INCREMENTAL
          replication-key: timestamp
        crypto_prices_2m:
          replication-method: INCREMENTAL
          replication-key: timestamp

        stock_prices_5m:
          replication-method: INCREMENTAL
          replication-key: timestamp
        futures_prices_5m:
          replication-method: INCREMENTAL
          replication-key: timestamp
        forex_prices_5m:
          replication-method: INCREMENTAL
          replication-key: timestamp
        crypto_prices_5m:
          replication-method: INCREMENTAL
          replication-key: timestamp

        stock_prices_1h:
          replication-method: INCREMENTAL
          replication-key: timestamp
        futures_prices_1h:
          replication-method: INCREMENTAL
          replication-key: timestamp
        forex_prices_1h:
          replication-method: INCREMENTAL
          replication-key: timestamp
        crypto_prices_1h:
          replication-method: INCREMENTAL
          replication-key: timestamp

        stock_prices_1d:
          replication-method: INCREMENTAL
          replication-key: timestamp
        futures_prices_1d:
          replication-method: INCREMENTAL
          replication-key: timestamp
        forex_prices_1d:
          replication-method: INCREMENTAL
          replication-key: timestamp
        crypto_prices_1d:
          replication-method: INCREMENTAL
          replication-key: timestamp


        ### financials ###

        actions:
          replication-method: INCREMENTAL
          replication-key: timestamp

        balance_sheet:
          replication-method: INCREMENTAL
          replication-key: date

        calendar:
          replication-method: INCREMENTAL
          replication-key: dividend_date

        cash_flow:
          replication-method: INCREMENTAL
          replication-key: date

        dividends:
          replication-method: INCREMENTAL
          replication-key: timestamp

        earnings_dates:
          replication-method: INCREMENTAL
          replication-key: timestamp

        fast_info:
          replication-method: INCREMENTAL
          replication-key: timestamp_extracted

        financials:
          replication-method: INCREMENTAL
          replication-key: date

        history_metadata:
          replication-method: INCREMENTAL
          replication-key: timestamp_extracted

        income_stmt:
          replication-method: INCREMENTAL
          replication-key: date

        insider_purchases:
          replication-method: INCREMENTAL
          replication-key: timestamp_extracted

        insider_roster_holders:
          replication-method: INCREMENTAL
          replication-key: latest_transaction_date

        insider_transactions:
          replication-method: INCREMENTAL
          replication-key: start_date

        institutional_holders:
          replication-method: INCREMENTAL
          replication-key: date_reported

        major_holders:
          replication-method: INCREMENTAL
          replication-key: timestamp_extracted

        mutualfund_holders:
          replication-method: INCREMENTAL
          replication-key: date_reported

        news:
          replication-method: INCREMENTAL
          replication-key: timestamp_extracted

        recommendations:
          replication-method: INCREMENTAL
          replication-key: timestamp_extracted

        shares_full:
          replication-method: INCREMENTAL
          replication-key: timestamp

        splits:
          replication-method: INCREMENTAL
          replication-key: timestamp

        option_chain:
          replication-method: INCREMENTAL
          replication-key: last_trade_date

        options:
          replication-method: INCREMENTAL
          replication-key: timestamp_extracted

        quarterly_balance_sheet:
          replication-method: INCREMENTAL
          replication-key: date

        quarterly_cash_flow:
          replication-method: INCREMENTAL
          replication-key: date

        quarterly_financials:
          replication-method: INCREMENTAL
          replication-key: date

        quarterly_income_stmt:
          replication-method: INCREMENTAL
          replication-key: date

        upgrades_downgrades:
          replication-method: INCREMENTAL
          replication-key: grade_date

  loaders:
    - name: target-jsonl
      variant: andyh1203
      pip_url: target-jsonl

    - name: target-bigquery
      variant: z3z1ma
      pip_url: git+https://github.com/z3z1ma/target-bigquery.git@f48f1d409a38e3d6669acec4cf3efe5b43763c9c
      config:
        method: ${TARGET_BIGQUERY_METHOD}
        project: ${GCP_PROJECT_ID}
        credentials_path: ${GOOGLE_APPLICATION_CREDENTIALS}
        dataset: ${GCP_DATASET}
        batch_size: ${TARGET_BIGQUERY_BATCH_SIZE}
        denormalized: true
        bucket: ${GCP_BUCKET_NAME}

    - name: target-snowflake
      variant: meltanolabs
      pip_url: git+https://github.com/MeltanoLabs/target-snowflake.git
      config:
        account: ${SNOWFLAKE_ACCOUNT}
        user: MELTANO
        password: ${SNOWFLAKE_PASSWORD}
        warehouse: ${SNOWFLAKE_WAREHOUSE}
        database: MELTANO
        role: MELTANO
        file_format: CSV_FORMAT
        batch_size_rows: ${SNOWFLAKE_BATCH_SIZE_ROWS}
