version: '3'

services:

  meltano-tap-yfinance:
    container_name: meltano-tap-yfinance
    image: meltano-tap-yfinance:latest
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - DOCKER_DEFAULT_PLATFORM=linux/amd64
    ports:
      - 5000:5000
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2800M