version: 1
send_anonymous_usage_stats: true
project_id: tap-yfinance

state_backend:
  type: remote
  uri: ${GCP_BUCKET_URI}
  gcs:
    application_credentials: ${GCP_TAP_YFINANCE_CREDENTIALS_PATH}

default_environment: dev
environments:
  - name: dev
    config:
      plugins:
        loaders:
          - name: target-snowflake
            env:
              TARGET_SNOWFLAKE_DEFAULT_TARGET_SCHEMA: TAP_YFINANCE_DEV

  - name: production
    config:
      plugins:
        loaders:
          - name: target-snowflake
            env:
              TARGET_SNOWFLAKE_DEFAULT_TARGET_SCHEMA: TAP_YFINANCE_PRODUCTION

plugins:
  extractors:
    - name: "tap-yfinance"
      namespace: "tap_yfinance"
      pip_url: -e .

      capabilities:
        - state
        - catalog
        - discover
        - about
        - stream-maps

      select:
        - stock_prices_1m
        - forex_prices_1m
        - crypto_prices_1m

      config:
        default_start_date: "1950-01-01"
        add_record_metadata: true
        financial_category:

          ### tickers ###

          tickers:
            stock_tickers:
              tickers: '*'
              schema_category: stock_tickers
            forex_tickers:
              tickers: '*'
              schema_category: forex_tickers
            crypto_tickers:
              tickers: '*'
              schema_category: crypto_tickers

          ### prices ###

          prices:
            ### long ###

            stock_prices_1m:
              tickers: ["AAPL", "META"]
              yf_params: { "interval": 1m, "prepost": true, "repair": true, "auto_adjust": true, "back_adjust": false }
              schema_category: stock_prices

            forex_prices_1m:
              tickers: ["EURUSD=X", "RUB=X"]
              yf_params: { "interval": 1m, "prepost": true, "repair": true, "auto_adjust": true, "back_adjust": false }
              schema_category: forex_prices

            crypto_prices_1m:
              tickers: ["BTC-USD", "ETH-USD"]
              yf_params: { "interval": 1m, "prepost": true, "repair": true, "auto_adjust": true, "back_adjust": false }
              schema_category: crypto_prices

            stock_prices_1d:
              tickers: ["AAPL", "META"]
              yf_params: { "interval": 1m, "prepost": true, "repair": true, "auto_adjust": true, "back_adjust": false }
              schema_category: stock_prices

            forex_prices_1d:
              tickers: ["EURUSD=X", "RUB=X"]
              yf_params: { "interval": 1m, "prepost": true, "repair": true, "auto_adjust": true, "back_adjust": false }
              schema_category: forex_prices

            crypto_prices_1d:
              tickers: ["BTC-USD", "ETH-USD"]
              yf_params: { "interval": 1m, "prepost": true, "repair": true, "auto_adjust": true, "back_adjust": false }
              schema_category: crypto_prices


      metadata:
        ### tickers ###

        stock_tickers:
          replication-method: INCREMENTAL
          replication-key: yahoo_ticker
        forex_tickers:
          replication-method: INCREMENTAL
          replication-key: yahoo_ticker
        crypto_tickers:
          replication-method: INCREMENTAL
          replication-key: yahoo_ticker

        ### prices ###

        stock_prices_1m:
          replication-method: INCREMENTAL
          replication-key: timestamp

        forex_prices_1m:
          replication-method: INCREMENTAL
          replication-key: timestamp

        crypto_prices_1m:
          replication-method: INCREMENTAL
          replication-key: timestamp

        ### prices wide ###

        stock_prices_1m_wide:
          replication-method: INCREMENTAL
          replication-key: timestamp

        forex_prices_1m_wide:
          replication-method: INCREMENTAL
          replication-key: timestamp

        crypto_prices_1m_wide:
          replication-method: INCREMENTAL
          replication-key: timestamp


  loaders:
    - name: target-jsonl
      variant: andyh1203
      pip_url: target-jsonl

    - name: target-bigquery
      variant: z3z1ma
      pip_url: git+https://github.com/z3z1ma/target-bigquery.git@a097d69545cbbb61a2b71bd2f26e5a8bc388ebc5
      config:
        project: ${GCP_PROJECT_ID}
        credentials_path: ${GCP_CREDENTIALS_PATH}
        dataset: meltano_yfinance
        batch_size: 10000
        denormalized: true

    - name: target-snowflake
      variant: meltanolabs
      pip_url: git+https://github.com/MeltanoLabs/target-snowflake.git@37639ef16ad5c70905c776a7834b133c7eeaa6f4
      config:
        account: ${SNOWFLAKE_ACCOUNT}
        user: ${SNOWFLAKE_USER}
        password: ${SNOWFLAKE_PASSWORD}
        warehouse: ${SNOWFLAKE_WAREHOUSE}
        database: ${SNOWFLAKE_DATABASE}
        role: ${SNOWFLAKE_ROLE}
        file_format: CSV_FORMAT
        batch_size_rows: 10000
