version: 1
send_anonymous_usage_stats: true
project_id: tap-yfinance

state_backend:
  type: remote
  uri: ${GCP_BUCKET_URI}
  gcs:
    application_credentials: ${GCP_TAP_YFINANCE_CREDENTIALS_PATH}

default_environment: dev

environments:
  - name: dev
    config:
      plugins:
        loaders:
          - name: target-snowflake
            env:
              TARGET_SNOWFLAKE_DEFAULT_TARGET_SCHEMA: MELTANO_YFINANCE_DEV

          - name: target-bigquery
            config:
              dataset: meltano_yfinance_dev

  - name: testing
    config:
      plugins:
        loaders:
          - name: target-snowflake
            env:
              TARGET_SNOWFLAKE_DEFAULT_TARGET_SCHEMA: MELTANO_YFINANCE_TESTING

          - name: target-bigquery
            config:
              dataset: meltano_yfinance_testing

  - name: staging
    config:
      plugins:
        loaders:
          - name: target-snowflake
            env:
              TARGET_SNOWFLAKE_DEFAULT_TARGET_SCHEMA: MELTANO_YFINANCE_STAGING

          - name: target-bigquery
            config:
              dataset: meltano_yfinance_staging

  - name: production
    config:
      plugins:
        loaders:
          - name: target-snowflake
            env:
              TARGET_SNOWFLAKE_DEFAULT_TARGET_SCHEMA: MELTANO_YFINANCE_PRODUCTION

          - name: target-bigquery
            config:
              dataset: meltano_yfinance_production

plugins:
  extractors:
    - name: "tap-yfinance"
      namespace: "tap_yfinance"
      pip_url: git+https://github.com/melgazar9/tap-yfinance.git

      capabilities:
        - state
        - catalog
        - discover
        - about
        - stream-maps

      select:
        - stock_tickers

      config:
        default_start_date: "1950-01-01"
        add_record_metadata: true
        financial_category:

          ### tickers ###

          tickers:
            stock_tickers:
              tickers: '*'
              schema_category: stock_tickers
            forex_tickers:
              tickers: '*'
              schema_category: forex_tickers
            crypto_tickers:
              tickers: '*'
              schema_category: crypto_tickers

          ### prices ###

          prices:

            ### long ###

            stock_prices_1m:
              tickers: '*'
              yf_params: { "interval": 1m, "prepost": true, "repair": true, "auto_adjust": true, "back_adjust": false }
              schema_category: stock_prices
            stock_prices_2m:
              tickers: '*'
              yf_params: { "interval": 2m, "prepost": true, "repair": true, "auto_adjust": true, "back_adjust": false }
              schema_category: stock_prices
            stock_prices_5m:
              tickers: '*'
              yf_params: { "interval": 5m, "prepost": true, "repair": true, "auto_adjust": true, "back_adjust": false }
              schema_category: stock_prices
            stock_prices_1h:
              tickers: '*'
              yf_params: { "interval": 1h, "prepost": true, "repair": true, "auto_adjust": true, "back_adjust": false }
              schema_category: stock_prices
            stock_prices_1d:
              tickers: '*'
              yf_params: { "interval": 1d, "prepost": true, "repair": true, "auto_adjust": true, "back_adjust": false }
              schema_category: stock_prices

            forex_prices_1m:
              tickers: '*'
              yf_params: { "interval": 1m, "prepost": true, "repair": true, "auto_adjust": true, "back_adjust": false }
              schema_category: forex_prices
            forex_prices_2m:
              tickers: '*'
              yf_params: { "interval": 2m, "prepost": true, "repair": true, "auto_adjust": true, "back_adjust": false }
              schema_category: forex_prices
            forex_prices_5m:
              tickers: '*'
              yf_params: { "interval": 5m, "prepost": true, "repair": true, "auto_adjust": true, "back_adjust": false }
              schema_category: forex_prices
            forex_prices_1h:
              tickers: '*'
              yf_params: { "interval": 1h, "prepost": true, "repair": true, "auto_adjust": true, "back_adjust": false }
              schema_category: forex_prices
            forex_prices_1d:
              tickers: '*'
              yf_params: { "interval": 1d, "prepost": true, "repair": true, "auto_adjust": true, "back_adjust": false }
              schema_category: forex_prices

            crypto_prices_1m:
              tickers: '*'
              yf_params: { "interval": 1m, "prepost": true, "repair": true, "auto_adjust": true, "back_adjust": false }
              schema_category: crypto_prices
            crypto_prices_2m:
              tickers: '*'
              yf_params: { "interval": 2m, "prepost": true, "repair": true, "auto_adjust": true, "back_adjust": false }
              schema_category: crypto_prices
            crypto_prices_5m:
              tickers: '*'
              yf_params: { "interval": 5m, "prepost": true, "repair": true, "auto_adjust": true, "back_adjust": false }
              schema_category: crypto_prices
            crypto_prices_1h:
              tickers: '*'
              yf_params: { "interval": 1h, "prepost": true, "repair": true, "auto_adjust": true, "back_adjust": false }
              schema_category: crypto_prices
            crypto_prices_1d:
              tickers: '*'
              yf_params: { "interval": 1d, "prepost": true, "repair": true, "auto_adjust": true, "back_adjust": false }
              schema_category: crypto_prices

            ### wide ###

            stock_prices_1m_wide:
              tickers: '*'
              yf_params: { "interval": 1m, "prepost": true, "repair": true, "auto_adjust": true, "back_adjust": false }
              schema_category: stock_prices_wide
            stock_prices_2m_wide:
              tickers: '*'
              yf_params: { "interval": 2m, "prepost": true, "repair": true, "auto_adjust": true, "back_adjust": false }
              schema_category: stock_prices_wide
            stock_prices_5m_wide:
              tickers: '*'
              yf_params: { "interval": 5m, "prepost": true, "repair": true, "auto_adjust": true, "back_adjust": false }
              schema_category: stock_prices_wide
            stock_prices_1h_wide:
              tickers: '*'
              yf_params: { "interval": 1h, "prepost": true, "repair": true, "auto_adjust": true, "back_adjust": false }
              schema_category: stock_prices_wide
            stock_prices_1d_wide:
              tickers: '*'
              yf_params: { "interval": 1d, "prepost": true, "repair": true, "auto_adjust": true, "back_adjust": false }
              schema_category: stock_prices_wide

            forex_prices_1m_wide:
              tickers: '*'
              yf_params: { "interval": 1m, "prepost": true, "repair": true, "auto_adjust": true, "back_adjust": false }
              schema_category: forex_prices_wide
            forex_prices_2m_wide:
              tickers: '*'
              yf_params: { "interval": 2m, "prepost": true, "repair": true, "auto_adjust": true, "back_adjust": false }
              schema_category: forex_prices_wide
            forex_prices_5m_wide:
              tickers: '*'
              yf_params: { "interval": 5m, "prepost": true, "repair": true, "auto_adjust": true, "back_adjust": false }
              schema_category: forex_prices_wide
            forex_prices_1h_wide:
              tickers: '*'
              yf_params: { "interval": 1h, "prepost": true, "repair": true, "auto_adjust": true, "back_adjust": false }
              schema_category: forex_prices_wide
            forex_prices_1d_wide:
              tickers: '*'
              yf_params: { "interval": 1d, "prepost": true, "repair": true, "auto_adjust": true, "back_adjust": false }
              schema_category: forex_prices_wide

            crypto_prices_1m_wide:
              tickers: '*'
              yf_params: { "interval": 1m, "prepost": true, "repair": true, "auto_adjust": true, "back_adjust": false }
              schema_category: crypto_prices_wide
            crypto_prices_2m_wide:
              tickers: '*'
              yf_params: { "interval": 2m, "prepost": true, "repair": true, "auto_adjust": true, "back_adjust": false }
              schema_category: crypto_prices_wide
            crypto_prices_5m_wide:
              tickers: '*'
              yf_params: { "interval": 5m, "prepost": true, "repair": true, "auto_adjust": true, "back_adjust": false }
              schema_category: crypto_prices_wide
            crypto_prices_1h_wide:
              tickers: '*'
              yf_params: { "interval": 1h, "prepost": true, "repair": true, "auto_adjust": true, "back_adjust": false }
              schema_category: crypto_prices_wide
            crypto_prices_1d_wide:
              tickers: '*'
              yf_params: { "interval": 1d, "prepost": true, "repair": true, "auto_adjust": true, "back_adjust": false }
              schema_category: crypto_prices_wide

        metadata:

          ### tickers ###

          stock_tickers:
            replication-method: INCREMENTAL
            replication-key: yahoo_ticker
          forex_tickers:
            replication-method: INCREMENTAL
            replication-key: yahoo_ticker
          crypto_tickers:
            replication-method: INCREMENTAL
            replication-key: yahoo_ticker

          ### prices ###

          stock_prices_1m:
            replication-method: INCREMENTAL
            replication-key: timestamp
          stock_prices_2m:
            replication-method: INCREMENTAL
            replication-key: timestamp
          stock_prices_5m:
            replication-method: INCREMENTAL
            replication-key: timestamp
          stock_prices_1h:
            replication-method: INCREMENTAL
            replication-key: timestamp
          stock_prices_1d:
            replication-method: INCREMENTAL
            replication-key: timestamp

          forex_prices_1m:
            replication-method: INCREMENTAL
            replication-key: timestamp
          forex_prices_2m:
            replication-method: INCREMENTAL
            replication-key: timestamp
          forex_prices_5m:
            replication-method: INCREMENTAL
            replication-key: timestamp
          forex_prices_1h:
            replication-method: INCREMENTAL
            replication-key: timestamp
          forex_prices_1d:
            replication-method: INCREMENTAL
            replication-key: timestamp

          crypto_prices_1m:
            replication-method: INCREMENTAL
            replication-key: timestamp
          crypto_prices_2m:
            replication-method: INCREMENTAL
            replication-key: timestamp
          crypto_prices_5m:
            replication-method: INCREMENTAL
            replication-key: timestamp
          crypto_prices_1h:
            replication-method: INCREMENTAL
            replication-key: timestamp
          crypto_prices_1d:
            replication-method: INCREMENTAL
            replication-key: timestamp

          ### prices wide ###

          stock_prices_1m_wide:
            replication-method: INCREMENTAL
            replication-key: timestamp
          stock_prices_2m_wide:
            replication-method: INCREMENTAL
            replication-key: timestamp
          stock_prices_5m_wide:
            replication-method: INCREMENTAL
            replication-key: timestamp
          stock_prices_1h_wide:
            replication-method: INCREMENTAL
            replication-key: timestamp
          stock_prices_1d_wide:
            replication-method: INCREMENTAL
            replication-key: timestamp

          forex_prices_1m_wide:
            replication-method: INCREMENTAL
            replication-key: timestamp
          forex_prices_2m_wide:
            replication-method: INCREMENTAL
            replication-key: timestamp
          forex_prices_5m_wide:
            replication-method: INCREMENTAL
            replication-key: timestamp
          forex_prices_1h_wide:
            replication-method: INCREMENTAL
            replication-key: timestamp
          forex_prices_1d_wide:
            replication-method: INCREMENTAL
            replication-key: timestamp

          crypto_prices_1m_wide:
            replication-method: INCREMENTAL
            replication-key: timestamp
          crypto_prices_2m_wide:
            replication-method: INCREMENTAL
            replication-key: timestamp
          crypto_prices_5m_wide:
            replication-method: INCREMENTAL
            replication-key: timestamp
          crypto_prices_1h_wide:
            replication-method: INCREMENTAL
            replication-key: timestamp
          crypto_prices_1d_wide:
            replication-method: INCREMENTAL
            replication-key: timestamp

  loaders:
    - name: target-bigquery
      variant: z3z1ma
      pip_url: git+https://github.com/z3z1ma/target-bigquery.git@a097d69545cbbb61a2b71bd2f26e5a8bc388ebc5
      config:
        project: ${GCP_PROJECT_ID}
        credentials_path: ${GCP_CREDENTIALS_PATH}
        dataset: meltano_yfinance
        batch_size: 10000
        denormalized: true

    - name: target-snowflake
      variant: meltanolabs
      pip_url: git+https://github.com/MeltanoLabs/target-snowflake.git@37639ef16ad5c70905c776a7834b133c7eeaa6f4
      config:
        account: ${SNOWFLAKE_ACCOUNT}
        user: ${SNOWFLAKE_USER}
        password: ${SNOWFLAKE_PASSWORD}
        warehouse: ${SNOWFLAKE_WAREHOUSE}
        database: ${SNOWFLAKE_DATABASE}
        role: ${SNOWFLAKE_ROLE}
        file_format: CSV_FORMAT
        batch_size_rows: 10000