{{ config(schema='yf_core', materialized='table', unique_key=['day', 'ticker']) }}

with cte as (
  select
    date(spi.timestamp) as day,
    spi.timestamp_tz_aware,
    spi.timezone,
    spi.ticker,
    spi.open,
    spi.high,
    spi.low,
    spi.close,
    spi.volume,
    spi.dividends,
    spi.stock_splits,
    a.dividends as a_dividends,
    a.stock_splits as a_stock_splits,
    bs.capital_stock as bs_capital_stock,
    bs.current_capital_lease_obligation as bs_current_capital_lease_obligation,
    bs.payables_and_accrued_expenses as bs_payables_and_accrued_expenses,
    bs.leases as bs_leases,
    bs.common_stock as bs_common_stock,
    bs.other_current_borrowings as bs_other_current_borrowings,
    bs.other_current_liabilities as bs_other_current_liabilities,
    bs.machinery_furniture_equipment as bs_machinery_furniture_equipment,
    bs.working_capital as bs_working_capital,
    bs.other_equity_adjustments as bs_other_equity_adjustments,
    bs.total_debt as bs_total_debt,
    bs.inventory as bs_inventory,
    bs.gains_losses_not_affecting_retained_earnings as bs_gains_losses_not_affecting_retained_earnings,
    bs.current_deferred_revenue as bs_current_deferred_revenue,
    bs.cash_financial as bs_cash_financial,
    bs.retained_earnings as bs_retained_earnings,
    bs.current_debt_and_capital_lease_obligation as bs_current_debt_and_capital_lease_obligation,
    bs.other_non_current_assets as bs_other_non_current_assets,
    bs.capital_lease_obligations as bs_capital_lease_obligations,
    bs.total_non_current_liabilities_net_minority_interest as bs_total_non_current_liabilities_net_minority_interest,
    bs.cash_equivalents as bs_cash_equivalents,
    bs.payables as bs_payables,
    bs.prepaid_assets as bs_prepaid_assets,
    bs.available_for_sale_securities as bs_available_for_sale_securities,
    bs.tangible_book_value as bs_tangible_book_value,
    bs.gross_accounts_receivable as bs_gross_accounts_receivable,
    bs.investments_and_advances as bs_investments_and_advances,
    bs.other_current_assets as bs_other_current_assets,
    bs.other_intangible_assets as bs_other_intangible_assets,
    bs.accounts_receivable as bs_accounts_receivable,
    bs.total_non_current_assets as bs_total_non_current_assets,
    bs.net_debt as bs_net_debt,
    bs.net_ppe as bs_net_ppe,
    bs.land_and_improvements as bs_land_and_improvements,
    bs.investmentin_financial_assets as bs_investmentin_financial_assets,
    bs.other_receivables as bs_other_receivables,
    bs.long_term_debt_and_capital_lease_obligation as bs_long_term_debt_and_capital_lease_obligation,
    bs.cash_cash_equivalents_and_short_term_investments as bs_cash_cash_equivalents_and_short_term_investments,
    bs.stockholders_equity as bs_stockholders_equity,
    bs.total_liabilities_net_minority_interest as bs_total_liabilities_net_minority_interest,
    bs.ordinary_shares_number as bs_ordinary_shares_number,
    bs.other_properties as bs_other_properties,
    bs.share_issued as bs_share_issued,
    bs.receivables as bs_receivables,
    bs.cash_and_cash_equivalents as bs_cash_and_cash_equivalents,
    bs.long_term_debt as bs_long_term_debt,
    bs.commercial_paper as bs_commercial_paper,
    bs.accumulated_depreciation as bs_accumulated_depreciation,
    bs.treasury_shares_number as bs_treasury_shares_number,
    bs.current_liabilities as bs_current_liabilities,
    bs.dueto_related_parties_current as bs_dueto_related_parties_current,
    bs.allowance_for_doubtful_accounts_receivable as bs_allowance_for_doubtful_accounts_receivable,
    bs.construction_in_progress as bs_construction_in_progress,
    bs.current_assets as bs_current_assets,
    bs.buildings_and_improvements as bs_buildings_and_improvements,
    bs.goodwill as bs_goodwill,
    bs.common_stock_equity as bs_common_stock_equity,
    bs.other_payable as bs_other_payable,
    bs.properties as bs_properties,
    bs.additional_paid_in_capital as bs_additional_paid_in_capital,
    bs.total_assets as bs_total_assets,
    bs.other_investments as bs_other_investments,
    bs.total_equity_gross_minority_interest as bs_total_equity_gross_minority_interest,
    bs.pensionand_other_post_retirement_benefit_plans_current as bs_pensionand_other_post_retirement_benefit_plans_current,
    bs.long_term_capital_lease_obligation as bs_long_term_capital_lease_obligation,
    bs.invested_capital as bs_invested_capital,
    bs.total_capitalization as bs_total_capitalization,
    bs.goodwill_and_other_intangible_assets as bs_goodwill_and_other_intangible_assets,
    bs.long_term_equity_investment as bs_long_term_equity_investment,
    bs.current_debt as bs_current_debt,
    bs.accounts_payable as bs_accounts_payable,
    bs.other_non_current_liabilities as bs_other_non_current_liabilities,
    bs.total_tax_payable as bs_total_tax_payable,
    bs.current_accrued_expenses as bs_current_accrued_expenses,
    bs.current_deferred_liabilities as bs_current_deferred_liabilities,
    bs.tradeand_other_payables_non_current as bs_tradeand_other_payables_non_current,
    bs.gross_ppe as bs_gross_ppe,
    bs.other_short_term_investments as bs_other_short_term_investments,
    bs.net_tangible_assets as bs_net_tangible_assets,
    bs.minority_interest as bs_minority_interest,
    bs.other_equity_interest as bs_other_equity_interest,
    bs.non_current_pension_and_other_postretirement_benefit_plans as bs_non_current_pension_and_other_postretirement_benefit_plans,
    bs.non_current_deferred_taxes_liabilities as bs_non_current_deferred_taxes_liabilities,
    bs.current_provisions as bs_current_provisions,
    bs.non_current_prepaid_assets as bs_non_current_prepaid_assets,
    bs.non_current_deferred_taxes_assets as bs_non_current_deferred_taxes_assets,
    bs.financial_assets as bs_financial_assets,
    bs.financial_assets_designatedas_fair_value_through_profitor_loss_ as bs_financial_assets_designated_as_fv_through_profitor_loss_,
    bs.investmentsin_associatesat_cost as bs_investmentsin_associatesat_cost,
    bs.hedging_assets_current as bs_hedging_assets_current,
    bs.finished_goods as bs_finished_goods,
    bs.work_in_process as bs_work_in_process,
    bs.raw_materials as bs_raw_materials,
    bs.taxes_receivable as bs_taxes_receivable,
    bs.preferred_shares_number as bs_preferred_shares_number,
    bs.preferred_stock_equity as bs_preferred_stock_equity,
    bs.preferred_stock as bs_preferred_stock,
    bs.derivative_product_liabilities as bs_derivative_product_liabilities,
    bs.non_current_deferred_revenue as bs_non_current_deferred_revenue,
    bs.long_term_provisions as bs_long_term_provisions,
    bs.investments_in_other_ventures_under_equity_method as bs_investments_in_other_ventures_under_equity_method,
    bs.investment_properties as bs_investment_properties,
    bs.assets_held_for_sale_current as bs_assets_held_for_sale_current,
    bs.inventories_adjustments_allowances as bs_inventories_adjustments_allowances,
    bs.other_inventories as bs_other_inventories,
    bs.fixed_assets_revaluation_reserve as bs_fixed_assets_revaluation_reserve,
    bs.held_to_maturity_securities as bs_held_to_maturity_securities,
    bs.investmentsin_joint_venturesat_cost as bs_investmentsin_joint_venturesat_cost,
    bs.receivables_adjustments_allowances as bs_receivables_adjustments_allowances,
    bs.defined_pension_benefit as bs_defined_pension_benefit,
    bs.non_current_accrued_expenses as bs_non_current_accrued_expenses,
    bs.treasury_stock as bs_treasury_stock,
    bs.investmentsin_subsidiariesat_cost as bs_investmentsin_subsidiariesat_cost,
    bs.restricted_cash as bs_restricted_cash,
    bs.current_deferred_taxes_liabilities as bs_current_deferred_taxes_liabilities,
    bs.employee_benefits as bs_employee_benefits,
    bs.non_current_deferred_liabilities as bs_non_current_deferred_liabilities,
    bs.dividends_payable as bs_dividends_payable,
    bs.income_tax_payable as bs_income_tax_payable,
    bs.non_current_deferred_assets as bs_non_current_deferred_assets,
    bs.non_current_accounts_receivable as bs_non_current_accounts_receivable,
    bs.trading_securities as bs_trading_securities,
    bs.line_of_credit as bs_line_of_credit,
    bs.interest_payable as bs_interest_payable,
    bs.non_current_note_receivables as bs_non_current_note_receivables,
    bs.loans_receivable as bs_loans_receivable,
    bs.preferred_securities_outside_stock_equity as bs_preferred_securities_outside_stock_equity,
    bs.duefrom_related_parties_non_current as bs_duefrom_related_parties_non_current,
    bs.duefrom_related_parties_current as bs_duefrom_related_parties_current,
    bs.accrued_interest_receivable as bs_accrued_interest_receivable,
    bs.current_deferred_assets as bs_current_deferred_assets,
    bs.foreign_currency_translation_adjustments as bs_foreign_currency_translation_adjustments,
    bs.liabilities_heldfor_sale_non_current as bs_liabilities_heldfor_sale_non_current,
    bs.current_deferred_taxes_assets as bs_current_deferred_taxes_assets,
    bs.minimum_pension_liabilities as bs_minimum_pension_liabilities,
    bs.current_notes_payable as bs_current_notes_payable,
    bs.notes_receivable as bs_notes_receivable,
    bs.unrealized_gain_loss as bs_unrealized_gain_loss,
    bs.general_partnership_capital as bs_general_partnership_capital,
    bs.limited_partnership_capital as bs_limited_partnership_capital,
    bs.total_partnership_capital as bs_total_partnership_capital,
    bs.dueto_related_parties_non_current as bs_dueto_related_parties_non_current,
    bs.restricted_common_stock as bs_restricted_common_stock,
    bs.other_capital_stock as bs_other_capital_stock,
    bs.financial_assets_designatedas_fv_thru_profitor_loss_total as bs_financial_assets_designatedas_fv_thru_profitor_loss_total,
    cd.dividend_date as cd_dividend_date,
    cd.ex_dividend_date as cd_ex_dividend_date,
    ce.earnings_date as ce_earnings_date,
    ce.earnings_high as ce_earnings_high,
    ce.earnings_low as ce_earnings_low,
    ce.earnings_average as ce_earnings_average,
    ce.revenue_high as ce_revenue_high,
    ce.revenue_low as ce_revenue_low,
    ce.revenue_average as ce_revenue_average,
    cf.beginning_cash_position as cf_beginning_cash_position,
    cf.capital_expenditure as cf_capital_expenditure,
    cf.cash_flow_from_continuing_financing_activities as cf_cash_flow_from_continuing_financing_activities,
    cf.cash_flow_from_continuing_investing_activities as cf_cash_flow_from_continuing_investing_activities,
    cf.cash_flow_from_continuing_operating_activities as cf_cash_flow_from_continuing_operating_activities,
    cf.change_in_account_payable as cf_change_in_account_payable,
    cf.change_in_inventory as cf_change_in_inventory,
    cf.change_in_other_current_assets as cf_change_in_other_current_assets,
    cf.change_in_other_current_liabilities as cf_change_in_other_current_liabilities,
    cf.change_in_payable as cf_change_in_payable,
    cf.change_in_payables_and_accrued_expense as cf_change_in_payables_and_accrued_expense,
    cf.change_in_receivables as cf_change_in_receivables,
    cf.change_in_working_capital as cf_change_in_working_capital,
    cf.changes_in_account_receivables as cf_changes_in_account_receivables,
    cf.changes_in_cash as cf_changes_in_cash,
    cf.common_stock_payments as cf_common_stock_payments,
    cf.depreciation_amortization_depletion as cf_depreciation_amortization_depletion,
    cf.depreciation_and_amortization as cf_depreciation_and_amortization,
    cf.end_cash_position as cf_end_cash_position,
    cf.financing_cash_flow as cf_financing_cash_flow,
    cf.free_cash_flow as cf_free_cash_flow,
    cf.income_tax_paid_supplemental_data as cf_income_tax_paid_supplemental_data,
    cf.interest_paid_supplemental_data as cf_interest_paid_supplemental_data,
    cf.investing_cash_flow as cf_investing_cash_flow,
    cf.issuance_of_debt as cf_issuance_of_debt,
    cf.long_term_debt_issuance as cf_long_term_debt_issuance,
    cf.long_term_debt_payments as cf_long_term_debt_payments,
    cf.net_common_stock_issuance as cf_net_common_stock_issuance,
    cf.net_income_from_continuing_operations as cf_net_income_from_continuing_operations,
    cf.net_investment_purchase_and_sale as cf_net_investment_purchase_and_sale,
    cf.net_issuance_payments_of_debt as cf_net_issuance_payments_of_debt,
    cf.net_long_term_debt_issuance as cf_net_long_term_debt_issuance,
    cf.net_other_financing_charges as cf_net_other_financing_charges,
    cf.net_other_investing_changes as cf_net_other_investing_changes,
    cf.net_ppe_purchase_and_sale as cf_net_ppe_purchase_and_sale,
    cf.operating_cash_flow as cf_operating_cash_flow,
    cf.other_non_cash_items as cf_other_non_cash_items,
    cf.purchase_of_investment as cf_purchase_of_investment,
    cf.purchase_of_ppe as cf_purchase_of_ppe,
    cf.repayment_of_debt as cf_repayment_of_debt,
    cf.repurchase_of_capital_stock as cf_repurchase_of_capital_stock,
    cf.sale_of_investment as cf_sale_of_investment,
    cf.stock_based_compensation as cf_stock_based_compensation,
    cf.purchase_of_business as cf_purchase_of_business,
    cf.sale_of_ppe as cf_sale_of_ppe,
    cf.common_stock_dividend_paid as cf_common_stock_dividend_paid,
    cf.deferred_tax as cf_deferred_tax,
    cf.change_in_other_working_capital as cf_change_in_other_working_capital,
    cf.change_in_prepaid_assets as cf_change_in_prepaid_assets,
    cf.cash_dividends_paid as cf_cash_dividends_paid,
    cf.effect_of_exchange_rate_changes as cf_effect_of_exchange_rate_changes,
    cf.short_term_debt_payments as cf_short_term_debt_payments,
    cf.deferred_income_tax as cf_deferred_income_tax,
    cf.net_business_purchase_and_sale as cf_net_business_purchase_and_sale,
    cf.unrealized_gain_loss_on_investment_securities as cf_unrealized_gain_loss_on_investment_securities,
    cf.asset_impairment_charge as cf_asset_impairment_charge,
    cf.change_in_accrued_expense as cf_change_in_accrued_expense,
    cf.amortization_cash_flow as cf_amortization_cash_flow,
    cf.depreciation as cf_depreciation,
    cf.dividend_received_cfo as cf_dividend_received_cfo,
    cf.gain_loss_on_investment_securities as cf_gain_loss_on_investment_securities,
    cf.gain_loss_on_sale_of_ppe as cf_gain_loss_on_sale_of_ppe,
    cf.interest_paid_cfo as cf_interest_paid_cfo,
    cf.interest_received_cfo as cf_interest_received_cfo,
    cf.net_foreign_currency_exchange_gain_loss as cf_net_foreign_currency_exchange_gain_loss,
    cf.net_intangibles_purchase_and_sale as cf_net_intangibles_purchase_and_sale,
    cf.net_investment_properties_purchase_and_sale as cf_net_investment_properties_purchase_and_sale,
    cf.other_cash_adjustment_outside_changein_cash as cf_other_cash_adjustment_outside_changein_cash,
    cf.pension_and_employee_benefit_expense as cf_pension_and_employee_benefit_expense,
    cf.provisionand_write_offof_assets as cf_provisionand_write_offof_assets,
    cf.purchase_of_intangibles as cf_purchase_of_intangibles,
    cf.purchase_of_investment_properties as cf_purchase_of_investment_properties,
    cf.sale_of_intangibles as cf_sale_of_intangibles,
    cf.short_term_debt_issuance as cf_short_term_debt_issuance,
    cf.taxes_refund_paid as cf_taxes_refund_paid,
    cf.classesof_cash_payments as cf_classesof_cash_payments,
    cf.cash_flowsfromusedin_operating_activities_direct as cf_cash_flowsfromusedin_operating_activities_direct,
    cf.classesof_cash_receiptsfrom_operating_activities as cf_classesof_cash_receiptsfrom_operating_activities,
    cf.interest_paid_cff as cf_interest_paid_cff,
    cf.interest_received_cfi as cf_interest_received_cfi,
    cf.other_cash_paymentsfrom_operating_activities as cf_other_cash_paymentsfrom_operating_activities,
    cf.paymentson_behalfof_employees as cf_paymentson_behalfof_employees,
    cf.paymentsto_suppliersfor_goodsand_services as cf_paymentsto_suppliersfor_goodsand_services,
    cf.receiptsfrom_customers as cf_receiptsfrom_customers,
    cf.taxes_refund_paid_direct as cf_taxes_refund_paid_direct,
    cf.sale_of_business as cf_sale_of_business,
    cf.common_stock_issuance as cf_common_stock_issuance,
    cf.issuance_of_capital_stock as cf_issuance_of_capital_stock,
    cf.sale_of_investment_properties as cf_sale_of_investment_properties,
    cf.dividends_received_cfi as cf_dividends_received_cfi,
    cf.amortization_of_intangibles as cf_amortization_of_intangibles,
    cf.operating_gains_losses as cf_operating_gains_losses,
    cf.proceeds_from_stock_option_exercised as cf_proceeds_from_stock_option_exercised,
    cf.capital_expenditure_reported as cf_capital_expenditure_reported,
    cf.interest_paid_direct as cf_interest_paid_direct,
    cf.earnings_losses_from_equity_investments as cf_earnings_losses_from_equity_investments,
    cf.gain_loss_on_sale_of_business as cf_gain_loss_on_sale_of_business,
    cf.other_cash_adjustment_inside_changein_cash as cf_other_cash_adjustment_inside_changein_cash,
    cf.net_preferred_stock_issuance as cf_net_preferred_stock_issuance,
    cf.preferred_stock_issuance as cf_preferred_stock_issuance,
    cf.amortization_of_securities as cf_amortization_of_securities,
    cf.change_in_income_tax_payable as cf_change_in_income_tax_payable,
    cf.change_in_tax_payable as cf_change_in_tax_payable,
    cf.dividend_paid_cfo as cf_dividend_paid_cfo,
    cf.preferred_stock_dividend_paid as cf_preferred_stock_dividend_paid,
    cf.cash_from_discontinued_operating_activities as cf_cash_from_discontinued_operating_activities,
    cf.preferred_stock_payments as cf_preferred_stock_payments,
    cf.cash_from_discontinued_investing_activities as cf_cash_from_discontinued_investing_activities,
    cf.change_in_interest_payable as cf_change_in_interest_payable,
    cf.cash_from_discontinued_financing_activities as cf_cash_from_discontinued_financing_activities,
    cf.other_cash_receiptsfrom_operating_activities as cf_other_cash_receiptsfrom_operating_activities,
    cf.cash_flow_from_discontinued_operation as cf_cash_flow_from_discontinued_operation,
    cf.interest_received_direct as cf_interest_received_direct,
    cf.excess_tax_benefit_from_stock_based_compensation as cf_excess_tax_benefit_from_stock_based_compensation,
    cf.depletion as cf_depletion,
    cf.change_in_dividend_payable as cf_change_in_dividend_payable,
    cf.receiptsfrom_government_grants as cf_receiptsfrom_government_grants,
    cf.dividends_received_direct as cf_dividends_received_direct,
    cf.net_short_term_debt_issuance as cf_net_short_term_debt_issuance,
    cf.dividends_paid_direct as cf_dividends_paid_direct,
    d.dividends as d_dividends,
    ed.eps_estimate as ed_eps_estimate,
    ed.reported_eps as ed_reported_eps,
    ed.pct_surprise as ed_pct_surprise,
    fi.currency as fi_currency,
    fi.day_high as fi_day_high,
    fi.day_low as fi_day_low,
    fi.exchange as fi_exchange,
    fi.fifty_day_average as fi_fifty_day_average,
    fi.last_price as fi_last_price,
    fi.last_volume as fi_last_volume,
    fi.market_cap as fi_market_cap,
    fi.open as fi_open,
    fi.previous_close as fi_previous_close,
    fi.quote_type as fi_quote_type,
    fi.regular_market_previous_close as fi_regular_market_previous_close,
    fi.shares as fi_shares,
    fi.ten_day_average_volume as fi_ten_day_average_volume,
    fi.three_month_average_volume as fi_three_month_average_volume,
    fi.extracted_timezone as fi_extracted_timezone,
    fi.two_hundred_day_average as fi_two_hundred_day_average,
    fi.year_change as fi_year_change,
    fi.year_high as fi_year_high,
    fi.year_low as fi_year_low,
    f.basic_average_shares as f_basic_average_shares,
    f.basic_eps as f_basic_eps,
    f.cost_of_revenue as f_cost_of_revenue,
    f.diluted_average_shares as f_diluted_average_shares,
    f.diluted_eps as f_diluted_eps,
    f.diluted_ni_availto_com_stockholders as f_diluted_ni_availto_com_stockholders,
    f.ebit as f_ebit,
    f.ebitda as f_ebitda,
    f.gross_profit as f_gross_profit,
    f.interest_expense as f_interest_expense,
    f.interest_expense_non_operating as f_interest_expense_non_operating,
    f.net_income as f_net_income,
    f.net_income_common_stockholders as f_net_income_common_stockholders,
    f.net_income_continuous_operations as f_net_income_continuous_operations,
    f.net_income_from_continuing_and_discontinued_operation as f_net_income_from_continuing_and_discontinued_operation,
    f.net_income_from_continuing_operation_net_minority_interest as f_net_income_from_continuing_operation_net_minority_interest,
    f.net_income_including_noncontrolling_interests as f_net_income_including_noncontrolling_interests,
    f.net_non_operating_interest_income_expense as f_net_non_operating_interest_income_expense,
    f.normalized_ebitda as f_normalized_ebitda,
    f.normalized_income as f_normalized_income,
    f.operating_expense as f_operating_expense,
    f.operating_income as f_operating_income,
    f.operating_revenue as f_operating_revenue,
    f.other_income_expense as f_other_income_expense,
    f.other_non_operating_income_expenses as f_other_non_operating_income_expenses,
    f.pretax_income as f_pretax_income,
    f.reconciled_cost_of_revenue as f_reconciled_cost_of_revenue,
    f.reconciled_depreciation as f_reconciled_depreciation,
    f.research_and_development as f_research_and_development,
    f.selling_general_and_administration as f_selling_general_and_administration,
    f.tax_effect_of_unusual_items as f_tax_effect_of_unusual_items,
    f.tax_provision as f_tax_provision,
    f.tax_rate_for_calcs as f_tax_rate_for_calcs,
    f.total_expenses as f_total_expenses,
    f.total_operating_income_as_reported as f_total_operating_income_as_reported,
    f.total_revenue as f_total_revenue,
    f.interest_income as f_interest_income,
    f.depreciation_and_amortization_in_income_statement as f_depreciation_and_amortization_in_income_statement,
    f.depreciation_amortization_depletion_income_statement as f_depreciation_amortization_depletion_income_statement,
    f.interest_income_non_operating as f_interest_income_non_operating,
    f.write_off as f_write_off,
    f.other_operating_expenses as f_other_operating_expenses,
    f.amortization_of_intangibles_income_statement as f_amortization_of_intangibles_income_statement,
    f.amortization as f_amortization,
    f.average_dilution_earnings as f_average_dilution_earnings,
    f.special_income_charges as f_special_income_charges,
    f.gain_on_sale_of_security as f_gain_on_sale_of_security,
    f.minority_interests as f_minority_interests,
    f.general_and_administrative_expense as f_general_and_administrative_expense,
    f.other_gand_a as f_other_gand_a,
    f.selling_and_marketing_expense as f_selling_and_marketing_expense,
    f.total_other_finance_cost as f_total_other_finance_cost,
    f.total_unusual_items as f_total_unusual_items,
    f.total_unusual_items_excluding_goodwill as f_total_unusual_items_excluding_goodwill,
    f.depreciation_income_statement as f_depreciation_income_statement,
    f.impairment_of_capital_assets as f_impairment_of_capital_assets,
    f.other_special_charges as f_other_special_charges,
    f.rent_and_landing_fees as f_rent_and_landing_fees,
    f.rent_expense_supplemental as f_rent_expense_supplemental,
    f.net_income_discontinuous_operations as f_net_income_discontinuous_operations,
    f.excise_taxes as f_excise_taxes,
    f.insurance_and_claims as f_insurance_and_claims,
    f.gain_on_sale_of_business as f_gain_on_sale_of_business,
    f.otherunder_preferred_stock_dividend as f_otherunder_preferred_stock_dividend,
    f.restructuring_and_mergern_acquisition as f_restructuring_and_mergern_acquisition,
    f.provision_for_doubtful_accounts as f_provision_for_doubtful_accounts,
    f.salaries_and_wages as f_salaries_and_wages,
    f.earnings_from_equity_interest as f_earnings_from_equity_interest,
    f.gain_on_sale_of_ppe as f_gain_on_sale_of_ppe,
    f.other_taxes as f_other_taxes,
    f.preferred_stock_dividends as f_preferred_stock_dividends,
    f.earnings_from_equity_interest_net_of_tax as f_earnings_from_equity_interest_net_of_tax,
    f.securities_amortization as f_securities_amortization,
    f.net_income_extraordinary as f_net_income_extraordinary,
    f.net_income_from_tax_loss_carryforward as f_net_income_from_tax_loss_carryforward,
    f.depletion_income_statement as f_depletion_income_statement,
    f.depreciation as f_depreciation,
    f.net_interest_income as f_net_interest_income,
    hmd.currency,
    hmd.exchange_name as hmd_exchange_name,
    hmd.instrument_type as hmd_instrument_type,
    hmd.first_trade_date as hmd_first_trade_date,
    hmd.regular_market_time as hmd_regular_market_time,
    hmd.gmtoffset as hmd_gmtoffset,
    hmd.exchange_timezone_name as hmd_exchange_timezone_name,
    hmd.regular_market_price as hmd_regular_market_price,
    hmd.chart_previous_close as hmd_chart_previous_close,
    hmd.previous_close as hmd_previous_close,
    hmd.scale as hmd_scale,
    hmd.price_hint as hmd_price_hint,
    hmd.current_trading_period as hmd_current_trading_period,
    hmd.trading_periods as hmd_trading_periods,
    hmd.data_granularity as hmd_data_granularity,
    hmd.range as hmd_range,
    hmd.valid_ranges as hmd_valid_ranges,
    hmd.current_trading_period_pre_timezone as hmd_current_trading_period_pre_timezone,
    hmd.current_trading_period_pre_start as hmd_current_trading_period_pre_start,
    hmd.current_trading_period_pre_end as hmd_current_trading_period_pre_end,
    hmd.current_trading_period_pre_gmtoffset as hmd_current_trading_period_pre_gmtoffset,
    hmd.current_trading_period_regular_timezone as hmd_current_trading_period_regular_timezone,
    hmd.current_trading_period_regular_start as hmd_current_trading_period_regular_start,
    hmd.current_trading_period_regular_end as hmd_current_trading_period_regular_end,
    hmd.current_trading_period_regular_gmtoffset as hmd_current_trading_period_regular_gmtoffset,
    hmd.current_trading_period_post_timezone as hmd_current_trading_period_post_timezone,
    hmd.current_trading_period_post_start as hmd_current_trading_period_post_start,
    hmd.current_trading_period_post_end as hmd_current_trading_period_post_end,
    hmd.current_trading_period_post_gmtoffset as hmd_current_trading_period_post_gmtoffset,
    hmd.trading_period_pre_start as hmd_trading_period_pre_start,
    hmd.trading_period_pre_end as hmd_trading_period_pre_end,
    hmd.trading_period_start as hmd_trading_period_start,
    hmd.trading_period_end as hmd_trading_period_end,
    hmd.trading_period_post_start as hmd_trading_period_post_start,
    hmd.trading_period_post_end as hmd_trading_period_post_end,
    hmd.full_exchange_name as hmd_full_exchange_name,
    hmd.has_pre_post_market_data as hmd_has_pre_post_market_data,
    hmd.fifty_two_week_high as hmd_fifty_two_week_high,
    hmd.fifty_two_week_low as hmd_fifty_two_week_low,
    hmd.regular_market_day_high as hmd_regular_market_day_high,
    hmd.regular_market_day_low as hmd_regular_market_day_low,
    hmd.regular_market_volume as hmd_regular_market_volume,
    ip.insider_purchases_last_6m as ip_insider_purchases_last_6m,
    ip.shares as ip_shares,
    ip.trans as ip_trans,
    ist.basic_average_shares as ist_basic_average_shares,
    ist.basic_eps as ist_basic_eps,
    ist.cost_of_revenue as ist_cost_of_revenue,
    ist.diluted_average_shares as ist_diluted_average_shares,
    ist.diluted_eps as ist_diluted_eps,
    ist.diluted_ni_availto_com_stockholders as ist_diluted_ni_availto_com_stockholders,
    ist.ebit as ist_ebit,
    ist.ebitda as ist_ebitda,
    ist.gross_profit as ist_gross_profit,
    ist.interest_expense as ist_interest_expense,
    ist.interest_expense_non_operating as ist_interest_expense_non_operating,
    ist.interest_income_non_operating as ist_interest_income_non_operating,
    ist.net_income as ist_net_income,
    ist.net_income_common_stockholders as ist_net_income_common_stockholders,
    ist.net_income_continuous_operations as ist_net_income_continuous_operations,
    ist.net_income_from_continuing_and_discontinued_operation as ist_net_income_from_continuing_and_discontinued_operation,
    ist.net_income_from_continuing_operation_net_minority_interest as ist_net_income_from_continuing_operation_net_minority_interest,
    ist.net_income_including_noncontrolling_interests as ist_net_income_including_noncontrolling_interests,
    ist.net_interest_income as ist_net_interest_income,
    ist.net_non_operating_interest_income_expense as ist_net_non_operating_interest_income_expense,
    ist.normalized_ebitda as ist_normalized_ebitda,
    ist.normalized_income as ist_normalized_income,
    ist.operating_expense as ist_operating_expense,
    ist.operating_income as ist_operating_income,
    ist.operating_revenue as ist_operating_revenue,
    ist.other_income_expense as ist_other_income_expense,
    ist.other_non_operating_income_expenses as ist_other_non_operating_income_expenses,
    ist.pretax_income as ist_pretax_income,
    ist.reconciled_cost_of_revenue as ist_reconciled_cost_of_revenue,
    ist.reconciled_depreciation as ist_reconciled_depreciation,
    ist.research_and_development as ist_research_and_development,
    ist.selling_general_and_administration as ist_selling_general_and_administration,
    ist.tax_effect_of_unusual_items as ist_tax_effect_of_unusual_items,
    ist.tax_provision as ist_tax_provision,
    ist.tax_rate_for_calcs as ist_tax_rate_for_calcs,
    ist.total_expenses as ist_total_expenses,
    ist.total_operating_income_as_reported as ist_total_operating_income_as_reported,
    ist.total_revenue as ist_total_revenue,
    ist.interest_income as ist_interest_income,
    ist.special_income_charges as ist_special_income_charges,
    ist.depreciation_and_amortization_in_income_statement as ist_depreciation_and_amortization_in_income_statement,
    ist.depreciation_amortization_depletion_income_statement as ist_depreciation_amortization_depletion_income_statement,
    ist.selling_and_marketing_expense as ist_selling_and_marketing_expense,
    ist.gain_on_sale_of_ppe as ist_gain_on_sale_of_ppe,
    ist.general_and_administrative_expense as ist_general_and_administrative_expense,
    ist.other_gand_a as ist_other_gand_a,
    ist.write_off as ist_write_off,
    ist.amortization_of_intangibles_income_statement as ist_amortization_of_intangibles_income_statement,
    ist.other_operating_expenses as ist_other_operating_expenses,
    ist.total_unusual_items_excluding_goodwill as ist_total_unusual_items_excluding_goodwill,
    ist.amortization as ist_amortization,
    ist.total_unusual_items as ist_total_unusual_items,
    ist.minority_interests as ist_minority_interests,
    ist.gain_on_sale_of_security as ist_gain_on_sale_of_security,
    ist.otherunder_preferred_stock_dividend as ist_otherunder_preferred_stock_dividend,
    ist.total_other_finance_cost as ist_total_other_finance_cost,
    ist.depreciation_income_statement as ist_depreciation_income_statement,
    ist.impairment_of_capital_assets as ist_impairment_of_capital_assets,
    ist.other_special_charges as ist_other_special_charges,
    ist.rent_and_landing_fees as ist_rent_and_landing_fees,
    ist.rent_expense_supplemental as ist_rent_expense_supplemental,
    ist.restructuring_and_mergern_acquisition as ist_restructuring_and_mergern_acquisition,
    ist.net_income_discontinuous_operations as ist_net_income_discontinuous_operations,
    ist.gain_on_sale_of_business as ist_gain_on_sale_of_business,
    ist.salaries_and_wages as ist_salaries_and_wages,
    ist.earnings_from_equity_interest_net_of_tax as ist_earnings_from_equity_interest_net_of_tax,
    ist.average_dilution_earnings as ist_average_dilution_earnings,
    ist.preferred_stock_dividends as ist_preferred_stock_dividends,
    ist.insurance_and_claims as ist_insurance_and_claims,
    ist.earnings_from_equity_interest as ist_earnings_from_equity_interest,
    ist.other_taxes as ist_other_taxes,
    ist.net_income_extraordinary as ist_net_income_extraordinary,
    ist.provision_for_doubtful_accounts as ist_provision_for_doubtful_accounts,
    ist.securities_amortization as ist_securities_amortization,
    ist.excise_taxes as ist_excise_taxes,
    ist.net_income_from_tax_loss_carryforward as ist_net_income_from_tax_loss_carryforward,
    ist.depletion_income_statement as ist_depletion_income_statement,
    ist.depreciation as ist_depreciation,
    irh.url as irh_url,
    irh.shares_owned_indirectly as irh_shares_owned_indirectly,
    irh.shares_owned_directly as irh_shares_owned_directly,
    irh.position_indirect_date as irh_position_indirect_date,
    irh.position_direct_date as irh_position_direct_date,
    irh.position as irh_position,
    irh.name as irh_name,
    irh.most_recent_transaction as irh_most_recent_transaction,
    irh.latest_transaction_date as irh_latest_transaction_date,
    it.start_date as it_start_date,
    it.shares as it_shares,
    it.url as it_url,
    it.text as it_text,
    it.insider as it_insider,
    it.position as it_position,
    it.transaction as it_transaction,
    it.ownership as it_ownership,
    it.value as it_value,
    ih.holder as ih_holder,
    ih.pct_out as ih_pct_out,
    ih.shares as ih_shares,
    ih.value as ih_value,
    mh.breakdown as mh_breakdown,
    mh.value as mh_value,
    mfh.holder as mfh_holder,
    mfh.pct_held as mfh_pct_held,
    mfh.shares as mfh_shares,
    mfh.value as mfh_value,
    news.id as news_id,
    news.content as news_content,
    qbs.capital_stock as qbs_capital_stock,
    qbs.current_capital_lease_obligation as qbs_current_capital_lease_obligation,
    qbs.payables_and_accrued_expenses as qbs_payables_and_accrued_expenses,
    qbs.leases as qbs_leases,
    qbs.common_stock as qbs_common_stock,
    qbs.other_current_borrowings as qbs_other_current_borrowings,
    qbs.other_current_liabilities as qbs_other_current_liabilities,
    qbs.machinery_furniture_equipment as qbs_machinery_furniture_equipment,
    qbs.working_capital as qbs_working_capital,
    qbs.other_equity_adjustments as qbs_other_equity_adjustments,
    qbs.total_debt as qbs_total_debt,
    qbs.inventory as qbs_inventory,
    qbs.gains_losses_not_affecting_retained_earnings as qbs_gains_losses_not_affecting_retained_earnings,
    qbs.current_deferred_revenue as qbs_current_deferred_revenue,
    qbs.cash_financial as qbs_cash_financial,
    qbs.retained_earnings as qbs_retained_earnings,
    qbs.current_debt_and_capital_lease_obligation as qbs_current_debt_and_capital_lease_obligation,
    qbs.other_non_current_assets as qbs_other_non_current_assets,
    qbs.capital_lease_obligations as qbs_capital_lease_obligations,
    qbs.total_non_current_liabilities_net_minority_interest as qbs_total_non_current_liabilities_net_minority_interest,
    qbs.cash_equivalents as qbs_cash_equivalents,
    qbs.payables as qbs_payables,
    qbs.prepaid_assets as qbs_prepaid_assets,
    qbs.available_for_sale_securities as qbs_available_for_sale_securities,
    qbs.tangible_book_value as qbs_tangible_book_value,
    qbs.gross_accounts_receivable as qbs_gross_accounts_receivable,
    qbs.investments_and_advances as qbs_investments_and_advances,
    qbs.other_current_assets as qbs_other_current_assets,
    qbs.other_intangible_assets as qbs_other_intangible_assets,
    qbs.accounts_receivable as qbs_accounts_receivable,
    qbs.total_non_current_assets as qbs_total_non_current_assets,
    qbs.net_debt as qbs_net_debt,
    qbs.net_ppe as qbs_net_ppe,
    qbs.land_and_improvements as qbs_land_and_improvements,
    qbs.investmentin_financial_assets as qbs_investmentin_financial_assets,
    qbs.other_receivables as qbs_other_receivables,
    qbs.long_term_debt_and_capital_lease_obligation as qbs_long_term_debt_and_capital_lease_obligation,
    qbs.cash_cash_equivalents_and_short_term_investments as qbs_cash_cash_equivalents_and_short_term_investments,
    qbs.stockholders_equity as qbs_stockholders_equity,
    qbs.total_liabilities_net_minority_interest as qbs_total_liabilities_net_minority_interest,
    qbs.ordinary_shares_number as qbs_ordinary_shares_number,
    qbs.other_properties as qbs_other_properties,
    qbs.share_issued as qbs_share_issued,
    qbs.receivables as qbs_receivables,
    qbs.cash_and_cash_equivalents as qbs_cash_and_cash_equivalents,
    qbs.long_term_debt as qbs_long_term_debt,
    qbs.commercial_paper as qbs_commercial_paper,
    qbs.accumulated_depreciation as qbs_accumulated_depreciation,
    qbs.treasury_shares_number as qbs_treasury_shares_number,
    qbs.current_liabilities as qbs_current_liabilities,
    qbs.dueto_related_parties_current as qbs_dueto_related_parties_current,
    qbs.allowance_for_doubtful_accounts_receivable as qbs_allowance_for_doubtful_accounts_receivable,
    qbs.construction_in_progress as qbs_construction_in_progress,
    qbs.current_assets as qbs_current_assets,
    qbs.buildings_and_improvements as qbs_buildings_and_improvements,
    qbs.goodwill as qbs_goodwill,
    qbs.common_stock_equity as qbs_common_stock_equity,
    qbs.other_payable as qbs_other_payable,
    qbs.properties as qbs_properties,
    qbs.additional_paid_in_capital as qbs_additional_paid_in_capital,
    qbs.total_assets as qbs_total_assets,
    qbs.other_investments as qbs_other_investments,
    qbs.total_equity_gross_minority_interest as qbs_total_equity_gross_minority_interest,
    qbs.pensionand_other_post_retirement_benefit_plans_current as qbs_pensionand_other_post_retirement_benefit_plans_current,
    qbs.long_term_capital_lease_obligation as qbs_long_term_capital_lease_obligation,
    qbs.invested_capital as qbs_invested_capital,
    qbs.total_capitalization as qbs_total_capitalization,
    qbs.goodwill_and_other_intangible_assets as qbs_goodwill_and_other_intangible_assets,
    qbs.long_term_equity_investment as qbs_long_term_equity_investment,
    qbs.current_debt as qbs_current_debt,
    qbs.accounts_payable as qbs_accounts_payable,
    qbs.other_non_current_liabilities as qbs_other_non_current_liabilities,
    qbs.total_tax_payable as qbs_total_tax_payable,
    qbs.current_accrued_expenses as qbs_current_accrued_expenses,
    qbs.current_deferred_liabilities as qbs_current_deferred_liabilities,
    qbs.tradeand_other_payables_non_current as qbs_tradeand_other_payables_non_current,
    qbs.gross_ppe as qbs_gross_ppe,
    qbs.other_short_term_investments as qbs_other_short_term_investments,
    qbs.net_tangible_assets as qbs_net_tangible_assets,
    qbs.minority_interest as qbs_minority_interest,
    qbs.other_equity_interest as qbs_other_equity_interest,
    qbs.non_current_pension_and_other_postretirement_benefit_plans as qbs_non_current_pension_and_other_postretirement_benefit_plans,
    qbs.non_current_deferred_taxes_liabilities as qbs_non_current_deferred_taxes_liabilities,
    qbs.current_provisions as qbs_current_provisions,
    qbs.non_current_prepaid_assets as qbs_non_current_prepaid_assets,
    qbs.non_current_deferred_taxes_assets as qbs_non_current_deferred_taxes_assets,
    qbs.financial_assets as qbs_financial_assets,
    qbs.financial_assets_designatedas_fv_thru_profitor_loss_total as qbs_financial_assets_designatedas_fv_thru_profitor_loss_total,
    qbs.investmentsin_associatesat_cost as qbs_investmentsin_associatesat_cost,
    qbs.hedging_assets_current as qbs_hedging_assets_current,
    qbs.finished_goods as qbs_finished_goods,
    qbs.work_in_process as qbs_work_in_process,
    qbs.raw_materials as qbs_raw_materials,
    qbs.taxes_receivable as qbs_taxes_receivable,
    qbs.preferred_shares_number as qbs_preferred_shares_number,
    qbs.preferred_stock_equity as qbs_preferred_stock_equity,
    qbs.preferred_stock as qbs_preferred_stock,
    qbs.derivative_product_liabilities as qbs_derivative_product_liabilities,
    qbs.non_current_deferred_revenue as qbs_non_current_deferred_revenue,
    qbs.long_term_provisions as qbs_long_term_provisions,
    qbs.investments_in_other_ventures_under_equity_method as qbs_investments_in_other_ventures_under_equity_method,
    qbs.investment_properties as qbs_investment_properties,
    qbs.assets_held_for_sale_current as qbs_assets_held_for_sale_current,
    qbs.inventories_adjustments_allowances as qbs_inventories_adjustments_allowances,
    qbs.other_inventories as qbs_other_inventories,
    qbs.fixed_assets_revaluation_reserve as qbs_fixed_assets_revaluation_reserve,
    qbs.held_to_maturity_securities as qbs_held_to_maturity_securities,
    qbs.investmentsin_joint_venturesat_cost as qbs_investmentsin_joint_venturesat_cost,
    qbs.receivables_adjustments_allowances as qbs_receivables_adjustments_allowances,
    qbs.defined_pension_benefit as qbs_defined_pension_benefit,
    qbs.non_current_accrued_expenses as qbs_non_current_accrued_expenses,
    qbs.treasury_stock as qbs_treasury_stock,
    qbs.investmentsin_subsidiariesat_cost as qbs_investmentsin_subsidiariesat_cost,
    qbs.restricted_cash as qbs_restricted_cash,
    qbs.current_deferred_taxes_liabilities as qbs_current_deferred_taxes_liabilities,
    qbs.employee_benefits as qbs_employee_benefits,
    qbs.non_current_deferred_liabilities as qbs_non_current_deferred_liabilities,
    qbs.dividends_payable as qbs_dividends_payable,
    qbs.income_tax_payable as qbs_income_tax_payable,
    qbs.non_current_deferred_assets as qbs_non_current_deferred_assets,
    qbs.non_current_accounts_receivable as qbs_non_current_accounts_receivable,
    qbs.trading_securities as qbs_trading_securities,
    qbs.line_of_credit as qbs_line_of_credit,
    qbs.interest_payable as qbs_interest_payable,
    qbs.non_current_note_receivables as qbs_non_current_note_receivables,
    qbs.loans_receivable as qbs_loans_receivable,
    qbs.preferred_securities_outside_stock_equity as qbs_preferred_securities_outside_stock_equity,
    qbs.duefrom_related_parties_non_current as qbs_duefrom_related_parties_non_current,
    qbs.duefrom_related_parties_current as qbs_duefrom_related_parties_current,
    qbs.accrued_interest_receivable as qbs_accrued_interest_receivable,
    qbs.current_deferred_assets as qbs_current_deferred_assets,
    qbs.foreign_currency_translation_adjustments as qbs_foreign_currency_translation_adjustments,
    qbs.liabilities_heldfor_sale_non_current as qbs_liabilities_heldfor_sale_non_current,
    qbs.current_deferred_taxes_assets as qbs_current_deferred_taxes_assets,
    qbs.minimum_pension_liabilities as qbs_minimum_pension_liabilities,
    qbs.current_notes_payable as qbs_current_notes_payable,
    qbs.notes_receivable as qbs_notes_receivable,
    qbs.unrealized_gain_loss as qbs_unrealized_gain_loss,
    qbs.general_partnership_capital as qbs_general_partnership_capital,
    qbs.limited_partnership_capital as qbs_limited_partnership_capital,
    qbs.total_partnership_capital as qbs_total_partnership_capital,
    qbs.dueto_related_parties_non_current as qbs_dueto_related_parties_non_current,
    qbs.restricted_common_stock as qbs_restricted_common_stock,
    qbs.other_capital_stock as qbs_other_capital_stock,
    qcf.beginning_cash_position as qcf_beginning_cash_position,
    qcf.capital_expenditure as qcf_capital_expenditure,
    qcf.cash_flow_from_continuing_financing_activities as qcf_cash_flow_from_continuing_financing_activities,
    qcf.cash_flow_from_continuing_investing_activities as qcf_cash_flow_from_continuing_investing_activities,
    qcf.cash_flow_from_continuing_operating_activities as qcf_cash_flow_from_continuing_operating_activities,
    qcf.change_in_account_payable as qcf_change_in_account_payable,
    qcf.change_in_inventory as qcf_change_in_inventory,
    qcf.change_in_other_current_assets as qcf_change_in_other_current_assets,
    qcf.change_in_other_current_liabilities as qcf_change_in_other_current_liabilities,
    qcf.change_in_payable as qcf_change_in_payable,
    qcf.change_in_payables_and_accrued_expense as qcf_change_in_payables_and_accrued_expense,
    qcf.change_in_receivables as qcf_change_in_receivables,
    qcf.change_in_working_capital as qcf_change_in_working_capital,
    qcf.changes_in_account_receivables as qcf_changes_in_account_receivables,
    qcf.changes_in_cash as qcf_changes_in_cash,
    qcf.common_stock_payments as qcf_common_stock_payments,
    qcf.depreciation_amortization_depletion as qcf_depreciation_amortization_depletion,
    qcf.depreciation_and_amortization as qcf_depreciation_and_amortization,
    qcf.end_cash_position as qcf_end_cash_position,
    qcf.financing_cash_flow as qcf_financing_cash_flow,
    qcf.free_cash_flow as qcf_free_cash_flow,
    qcf.income_tax_paid_supplemental_data as qcf_income_tax_paid_supplemental_data,
    qcf.interest_paid_supplemental_data as qcf_interest_paid_supplemental_data,
    qcf.investing_cash_flow as qcf_investing_cash_flow,
    qcf.issuance_of_debt as qcf_issuance_of_debt,
    qcf.long_term_debt_issuance as qcf_long_term_debt_issuance,
    qcf.long_term_debt_payments as qcf_long_term_debt_payments,
    qcf.net_common_stock_issuance as qcf_net_common_stock_issuance,
    qcf.net_income_from_continuing_operations as qcf_net_income_from_continuing_operations,
    qcf.net_investment_purchase_and_sale as qcf_net_investment_purchase_and_sale,
    qcf.net_issuance_payments_of_debt as qcf_net_issuance_payments_of_debt,
    qcf.net_long_term_debt_issuance as qcf_net_long_term_debt_issuance,
    qcf.net_other_financing_charges as qcf_net_other_financing_charges,
    qcf.net_other_investing_changes as qcf_net_other_investing_changes,
    qcf.net_ppe_purchase_and_sale as qcf_net_ppe_purchase_and_sale,
    qcf.operating_cash_flow as qcf_operating_cash_flow,
    qcf.other_non_cash_items as qcf_other_non_cash_items,
    qcf.purchase_of_investment as qcf_purchase_of_investment,
    qcf.purchase_of_ppe as qcf_purchase_of_ppe,
    qcf.repayment_of_debt as qcf_repayment_of_debt,
    qcf.repurchase_of_capital_stock as qcf_repurchase_of_capital_stock,
    qcf.sale_of_investment as qcf_sale_of_investment,
    qcf.stock_based_compensation as qcf_stock_based_compensation,
    qcf.purchase_of_business as qcf_purchase_of_business,
    qcf.sale_of_ppe as qcf_sale_of_ppe,
    qcf.common_stock_dividend_paid as qcf_common_stock_dividend_paid,
    qcf.deferred_tax as qcf_deferred_tax,
    qcf.change_in_other_working_capital as qcf_change_in_other_working_capital,
    qcf.change_in_prepaid_assets as qcf_change_in_prepaid_assets,
    qcf.cash_dividends_paid as qcf_cash_dividends_paid,
    qcf.effect_of_exchange_rate_changes as qcf_effect_of_exchange_rate_changes,
    qcf.short_term_debt_payments as qcf_short_term_debt_payments,
    qcf.deferred_income_tax as qcf_deferred_income_tax,
    qcf.net_business_purchase_and_sale as qcf_net_business_purchase_and_sale,
    qcf.unrealized_gain_loss_on_investment_securities as qcf_unrealized_gain_loss_on_investment_securities,
    qcf.asset_impairment_charge as qcf_asset_impairment_charge,
    qcf.change_in_accrued_expense as qcf_change_in_accrued_expense,
    qcf.amortization_cash_flow as qcf_amortization_cash_flow,
    qcf.depreciation as qcf_depreciation,
    qcf.dividend_received_cfo as qcf_dividend_received_cfo,
    qcf.gain_loss_on_investment_securities as qcf_gain_loss_on_investment_securities,
    qcf.gain_loss_on_sale_of_ppe as qcf_gain_loss_on_sale_of_ppe,
    qcf.interest_paid_cfo as qcf_interest_paid_cfo,
    qcf.interest_received_cfo as qcf_interest_received_cfo,
    qcf.net_foreign_currency_exchange_gain_loss as qcf_net_foreign_currency_exchange_gain_loss,
    qcf.net_intangibles_purchase_and_sale as qcf_net_intangibles_purchase_and_sale,
    qcf.net_investment_properties_purchase_and_sale as qcf_net_investment_properties_purchase_and_sale,
    qcf.other_cash_adjustment_outside_changein_cash as qcf_other_cash_adjustment_outside_changein_cash,
    qcf.pension_and_employee_benefit_expense as qcf_pension_and_employee_benefit_expense,
    qcf.provisionand_write_offof_assets as qcf_provisionand_write_offof_assets,
    qcf.purchase_of_intangibles as qcf_purchase_of_intangibles,
    qcf.purchase_of_investment_properties as qcf_purchase_of_investment_properties,
    qcf.sale_of_intangibles as qcf_sale_of_intangibles,
    qcf.short_term_debt_issuance as qcf_short_term_debt_issuance,
    qcf.taxes_refund_paid as qcf_taxes_refund_paid,
    qcf.classesof_cash_payments as qcf_classesof_cash_payments,
    qcf.cash_flowsfromusedin_operating_activities_direct as qcf_cash_flowsfromusedin_operating_activities_direct,
    qcf.classesof_cash_receiptsfrom_operating_activities as qcf_classesof_cash_receiptsfrom_operating_activities,
    qcf.interest_paid_cff as qcf_interest_paid_cff,
    qcf.interest_received_cfi as qcf_interest_received_cfi,
    qcf.other_cash_paymentsfrom_operating_activities as qcf_other_cash_paymentsfrom_operating_activities,
    qcf.paymentson_behalfof_employees as qcf_paymentson_behalfof_employees,
    qcf.paymentsto_suppliersfor_goodsand_services as qcf_paymentsto_suppliersfor_goodsand_services,
    qcf.receiptsfrom_customers as qcf_receiptsfrom_customers,
    qcf.taxes_refund_paid_direct as qcf_taxes_refund_paid_direct,
    qcf.sale_of_business as qcf_sale_of_business,
    qcf.common_stock_issuance as qcf_common_stock_issuance,
    qcf.issuance_of_capital_stock as qcf_issuance_of_capital_stock,
    qcf.sale_of_investment_properties as qcf_sale_of_investment_properties,
    qcf.dividends_received_cfi as qcf_dividends_received_cfi,
    qcf.amortization_of_intangibles as qcf_amortization_of_intangibles,
    qcf.operating_gains_losses as qcf_operating_gains_losses,
    qcf.proceeds_from_stock_option_exercised as qcf_proceeds_from_stock_option_exercised,
    qcf.capital_expenditure_reported as qcf_capital_expenditure_reported,
    qcf.interest_paid_direct as qcf_interest_paid_direct,
    qcf.earnings_losses_from_equity_investments as qcf_earnings_losses_from_equity_investments,
    qcf.gain_loss_on_sale_of_business as qcf_gain_loss_on_sale_of_business,
    qcf.other_cash_adjustment_inside_changein_cash as qcf_other_cash_adjustment_inside_changein_cash,
    qcf.net_preferred_stock_issuance as qcf_net_preferred_stock_issuance,
    qcf.preferred_stock_issuance as qcf_preferred_stock_issuance,
    qcf.amortization_of_securities as qcf_amortization_of_securities,
    qcf.change_in_income_tax_payable as qcf_change_in_income_tax_payable,
    qcf.change_in_tax_payable as qcf_change_in_tax_payable,
    qcf.dividend_paid_cfo as qcf_dividend_paid_cfo,
    qcf.preferred_stock_dividend_paid as qcf_preferred_stock_dividend_paid,
    qcf.cash_from_discontinued_operating_activities as qcf_cash_from_discontinued_operating_activities,
    qcf.preferred_stock_payments as qcf_preferred_stock_payments,
    qcf.cash_from_discontinued_investing_activities as qcf_cash_from_discontinued_investing_activities,
    qcf.change_in_interest_payable as qcf_change_in_interest_payable,
    qcf.cash_from_discontinued_financing_activities as qcf_cash_from_discontinued_financing_activities,
    qcf.other_cash_receiptsfrom_operating_activities as qcf_other_cash_receiptsfrom_operating_activities,
    qcf.cash_flow_from_discontinued_operation as qcf_cash_flow_from_discontinued_operation,
    qcf.interest_received_direct as qcf_interest_received_direct,
    qcf.excess_tax_benefit_from_stock_based_compensation as qcf_excess_tax_benefit_from_stock_based_compensation,
    qcf.depletion as qcf_depletion,
    qcf.change_in_dividend_payable as qcf_change_in_dividend_payable,
    qcf.receiptsfrom_government_grants as qcf_receiptsfrom_government_grants,
    qcf.dividends_received_direct as qcf_dividends_received_direct,
    qcf.net_short_term_debt_issuance as qcf_net_short_term_debt_issuance,
    qcf.dividends_paid_direct as qcf_dividends_paid_direct,
    qf.basic_average_shares as qf_basic_average_shares,
    qf.basic_eps as qf_basic_eps,
    qf.cost_of_revenue as qf_cost_of_revenue,
    qf.diluted_average_shares as qf_diluted_average_shares,
    qf.diluted_eps as qf_diluted_eps,
    qf.diluted_ni_availto_com_stockholders as qf_diluted_ni_availto_com_stockholders,
    qf.ebit as qf_ebit,
    qf.ebitda as qf_ebitda,
    qf.gross_profit as qf_gross_profit,
    qf.interest_expense as qf_interest_expense,
    qf.interest_expense_non_operating as qf_interest_expense_non_operating,
    qf.net_income as qf_net_income,
    qf.net_income_common_stockholders as qf_net_income_common_stockholders,
    qf.net_income_continuous_operations as qf_net_income_continuous_operations,
    qf.net_income_from_continuing_and_discontinued_operation as qf_net_income_from_continuing_and_discontinued_operation,
    qf.net_income_from_continuing_operation_net_minority_interest as qf_net_income_from_continuing_operation_net_minority_interest,
    qf.net_income_including_noncontrolling_interests as qf_net_income_including_noncontrolling_interests,
    qf.net_non_operating_interest_income_expense as qf_net_non_operating_interest_income_expense,
    qf.normalized_ebitda as qf_normalized_ebitda,
    qf.normalized_income as qf_normalized_income,
    qf.operating_expense as qf_operating_expense,
    qf.operating_income as qf_operating_income,
    qf.operating_revenue as qf_operating_revenue,
    qf.other_income_expense as qf_other_income_expense,
    qf.other_non_operating_income_expenses as qf_other_non_operating_income_expenses,
    qf.pretax_income as qf_pretax_income,
    qf.reconciled_cost_of_revenue as qf_reconciled_cost_of_revenue,
    qf.reconciled_depreciation as qf_reconciled_depreciation,
    qf.research_and_development as qf_research_and_development,
    qf.selling_general_and_administration as qf_selling_general_and_administration,
    qf.tax_effect_of_unusual_items as qf_tax_effect_of_unusual_items,
    qf.tax_provision as qf_tax_provision,
    qf.tax_rate_for_calcs as qf_tax_rate_for_calcs,
    qf.total_expenses as qf_total_expenses,
    qf.total_operating_income_as_reported as qf_total_operating_income_as_reported,
    qf.total_revenue as qf_total_revenue,
    qf.interest_income as qf_interest_income,
    qf.depreciation_and_amortization_in_income_statement as qf_depreciation_and_amortization_in_income_statement,
    qf.depreciation_amortization_depletion_income_statement as qf_depreciation_amortization_depletion_income_statement,
    qf.interest_income_non_operating as qf_interest_income_non_operating,
    qf.write_off as qf_write_off,
    qf.other_operating_expenses as qf_other_operating_expenses,
    qf.amortization_of_intangibles_income_statement as qf_amortization_of_intangibles_income_statement,
    qf.amortization as qf_amortization,
    qf.average_dilution_earnings as qf_average_dilution_earnings,
    qf.special_income_charges as qf_special_income_charges,
    qf.gain_on_sale_of_security as qf_gain_on_sale_of_security,
    qf.minority_interests as qf_minority_interests,
    qf.general_and_administrative_expense as qf_general_and_administrative_expense,
    qf.other_gand_a as qf_other_gand_a,
    qf.selling_and_marketing_expense as qf_selling_and_marketing_expense,
    qf.total_other_finance_cost as qf_total_other_finance_cost,
    qf.total_unusual_items as qf_total_unusual_items,
    qf.total_unusual_items_excluding_goodwill as qf_total_unusual_items_excluding_goodwill,
    qf.depreciation_income_statement as qf_depreciation_income_statement,
    qf.impairment_of_capital_assets as qf_impairment_of_capital_assets,
    qf.other_special_charges as qf_other_special_charges,
    qf.rent_and_landing_fees as qf_rent_and_landing_fees,
    qf.rent_expense_supplemental as qf_rent_expense_supplemental,
    qf.net_income_discontinuous_operations as qf_net_income_discontinuous_operations,
    qf.excise_taxes as qf_excise_taxes,
    qf.insurance_and_claims as qf_insurance_and_claims,
    qf.gain_on_sale_of_business as qf_gain_on_sale_of_business,
    qf.otherunder_preferred_stock_dividend as qf_otherunder_preferred_stock_dividend,
    qf.restructuring_and_mergern_acquisition as qf_restructuring_and_mergern_acquisition,
    qf.provision_for_doubtful_accounts as qf_provision_for_doubtful_accounts,
    qf.salaries_and_wages as qf_salaries_and_wages,
    qf.earnings_from_equity_interest as qf_earnings_from_equity_interest,
    qf.gain_on_sale_of_ppe as qf_gain_on_sale_of_ppe,
    qf.other_taxes as qf_other_taxes,
    qf.preferred_stock_dividends as qf_preferred_stock_dividends,
    qf.earnings_from_equity_interest_net_of_tax as qf_earnings_from_equity_interest_net_of_tax,
    qf.securities_amortization as qf_securities_amortization,
    qf.net_income_extraordinary as qf_net_income_extraordinary,
    qf.net_income_from_tax_loss_carryforward as qf_net_income_from_tax_loss_carryforward,
    qf.depletion_income_statement as qf_depletion_income_statement,
    qf.depreciation as qf_depreciation,
    qf.net_interest_income as qf_net_interest_income,
    qis.basic_average_shares as qis_basic_average_shares,
    qis.basic_eps as qis_basic_eps,
    qis.cost_of_revenue as qis_cost_of_revenue,
    qis.diluted_average_shares as qis_diluted_average_shares,
    qis.diluted_eps as qis_diluted_eps,
    qis.diluted_ni_availto_com_stockholders as qis_diluted_ni_availto_com_stockholders,
    qis.ebit as qis_ebit,
    qis.ebitda as qis_ebitda,
    qis.gross_profit as qis_gross_profit,
    qis.interest_expense as qis_interest_expense,
    qis.interest_expense_non_operating as qis_interest_expense_non_operating,
    qis.interest_income_non_operating as qis_interest_income_non_operating,
    qis.net_income as qis_net_income,
    qis.net_income_common_stockholders as qis_net_income_common_stockholders,
    qis.net_income_continuous_operations as qis_net_income_continuous_operations,
    qis.net_income_from_continuing_and_discontinued_operation as qis_net_income_from_continuing_and_discontinued_operation,
    qis.net_income_from_continuing_operation_net_minority_interest as qis_net_income_from_continuing_operation_net_minority_interest,
    qis.net_income_including_noncontrolling_interests as qis_net_income_including_noncontrolling_interests,
    qis.net_interest_income as qis_net_interest_income,
    qis.net_non_operating_interest_income_expense as qis_net_non_operating_interest_income_expense,
    qis.normalized_ebitda as qis_normalized_ebitda,
    qis.normalized_income as qis_normalized_income,
    qis.operating_expense as qis_operating_expense,
    qis.operating_income as qis_operating_income,
    qis.operating_revenue as qis_operating_revenue,
    qis.other_income_expense as qis_other_income_expense,
    qis.other_non_operating_income_expenses as qis_other_non_operating_income_expenses,
    qis.pretax_income as qis_pretax_income,
    qis.reconciled_cost_of_revenue as qis_reconciled_cost_of_revenue,
    qis.reconciled_depreciation as qis_reconciled_depreciation,
    qis.research_and_development as qis_research_and_development,
    qis.selling_general_and_administration as qis_selling_general_and_administration,
    qis.tax_effect_of_unusual_items as qis_tax_effect_of_unusual_items,
    qis.tax_provision as qis_tax_provision,
    qis.tax_rate_for_calcs as qis_tax_rate_for_calcs,
    qis.total_expenses as qis_total_expenses,
    qis.total_operating_income_as_reported as qis_total_operating_income_as_reported,
    qis.total_revenue as qis_total_revenue,
    qis.interest_income as qis_interest_income,
    qis.special_income_charges as qis_special_income_charges,
    qis.depreciation_and_amortization_in_income_statement as qis_depreciation_and_amortization_in_income_statement,
    qis.depreciation_amortization_depletion_income_statement as qis_depreciation_amortization_depletion_income_statement,
    qis.selling_and_marketing_expense as qis_selling_and_marketing_expense,
    qis.gain_on_sale_of_ppe as qis_gain_on_sale_of_ppe,
    qis.general_and_administrative_expense as qis_general_and_administrative_expense,
    qis.other_gand_a as qis_other_gand_a,
    qis.write_off as qis_write_off,
    qis.amortization_of_intangibles_income_statement as qis_amortization_of_intangibles_income_statement,
    qis.other_operating_expenses as qis_other_operating_expenses,
    qis.total_unusual_items_excluding_goodwill as qis_total_unusual_items_excluding_goodwill,
    qis.amortization as qis_amortization,
    qis.total_unusual_items as qis_total_unusual_items,
    qis.minority_interests as qis_minority_interests,
    qis.gain_on_sale_of_security as qis_gain_on_sale_of_security,
    qis.otherunder_preferred_stock_dividend as qis_otherunder_preferred_stock_dividend,
    qis.total_other_finance_cost as qis_total_other_finance_cost,
    qis.depreciation_income_statement as qis_depreciation_income_statement,
    qis.impairment_of_capital_assets as qis_impairment_of_capital_assets,
    qis.other_special_charges as qis_other_special_charges,
    qis.rent_and_landing_fees as qis_rent_and_landing_fees,
    qis.rent_expense_supplemental as qis_rent_expense_supplemental,
    qis.restructuring_and_mergern_acquisition as qis_restructuring_and_mergern_acquisition,
    qis.net_income_discontinuous_operations as qis_net_income_discontinuous_operations,
    qis.gain_on_sale_of_business as qis_gain_on_sale_of_business,
    qis.salaries_and_wages as qis_salaries_and_wages,
    qis.earnings_from_equity_interest_net_of_tax as qis_earnings_from_equity_interest_net_of_tax,
    qis.average_dilution_earnings as qis_average_dilution_earnings,
    qis.preferred_stock_dividends as qis_preferred_stock_dividends,
    qis.insurance_and_claims as qis_insurance_and_claims,
    qis.earnings_from_equity_interest as qis_earnings_from_equity_interest,
    qis.other_taxes as qis_other_taxes,
    qis.net_income_extraordinary as qis_net_income_extraordinary,
    qis.provision_for_doubtful_accounts as qis_provision_for_doubtful_accounts,
    qis.securities_amortization as qis_securities_amortization,
    qis.excise_taxes as qis_excise_taxes,
    qis.net_income_from_tax_loss_carryforward as qis_net_income_from_tax_loss_carryforward,
    qis.depletion_income_statement as qis_depletion_income_statement,
    qis.depreciation as qis_depreciation,
    rec.period as rec_period,
    rec.strong_buy as rec_strong_buy,
    rec.buy as rec_buy,
    rec.hold as rec_hold,
    rec.sell as rec_sell,
    rec.strong_sell as rec_strong_sell,
    sf.amount as sf_amount,
    sp.stock_splits as sp_stock_splits,
    ud.grade_date as ud_grade_date,
    ud.firm as ud_firm,
    ud.to_grade as ud_to_grade,
    ud.from_grade as ud_from_grade,
    ud.action as ud_action

  from
    {{ ref('yf_stock_prices_1d') }} spi

  left join (
    select * from (
      select *, row_number() over(partition by date(timestamp), ticker order by _sdc_batched_at desc) as rn
        from {{ ref('yf_actions') }}
      ) a2
    where a2.rn = 1
  ) a on spi.ticker = a.ticker and date(spi.timestamp) = date(a.timestamp)

  left join {{ ref('yf_balance_sheet') }} bs on spi.ticker = bs.ticker and date(spi.timestamp) = date(bs.date)
  left join (select distinct dividend_date, ex_dividend_date, ticker from {{ ref('yf_calendar') }}) cd on spi.ticker = cd.ticker and date(spi.timestamp) = date(cd.dividend_date)
  left join (select distinct ticker, earnings_date, earnings_high, earnings_low, earnings_average, revenue_high, revenue_low, revenue_average from {{ ref('yf_calendar') }}) ce on spi.ticker = ce.ticker and date(spi.timestamp) = date(ce.earnings_date)
  left join {{ ref('yf_cash_flow') }} cf on spi.ticker = cf.ticker and date(spi.timestamp) = date(cf.date)
  left join {{ ref('yf_dividends') }} d on spi.ticker = d.ticker and date(spi.timestamp) = date(d.timestamp)

  left join (
    select * from (
      select *, date(timestamp) as day, row_number() over(partition by date(timestamp), ticker order by _sdc_batched_at desc) as rn
        from {{ ref('yf_earnings_dates') }}
      ) ed2
    where ed2.rn = 1
  ) ed on spi.ticker = ed.ticker and date(spi.timestamp) = date(ed.day)

  left join (
    select * from (
      select *, date(timestamp_extracted) as day, row_number() over(partition by date(timestamp_extracted), ticker order by timestamp_extracted desc) as rn
        from {{ ref('yf_fast_info') }}
      ) fi2
    where fi2.rn = 1
  ) fi on spi.ticker = fi.ticker and date(spi.timestamp) = date(fi.day)

  left join {{ ref('yf_financials') }} f on spi.ticker = f.ticker and date(spi.timestamp) = date(f.date)

  left join (
    select * from (
      select *, date(timestamp_extracted) as day, row_number() over(partition by date(timestamp_extracted), ticker order by timestamp_extracted desc) as rn
        from {{ ref('yf_history_metadata') }}
      ) hmd2
    where hmd2.rn = 1
  ) hmd on spi.ticker = hmd.ticker and date(spi.timestamp) = date(hmd.day)

  left join {{ ref('yf_income_stmt') }} ist on spi.ticker = ist.ticker and date(spi.timestamp) = date(ist.date)

  left join {{ ref('yf_insider_purchases') }} ip on spi.ticker = ip.ticker and date(spi.timestamp) = date(ip.date_extracted)

  left join (
    select * from (
      select *, date(latest_transaction_date) as day, row_number() over(partition by date(latest_transaction_date), ticker order by _sdc_batched_at desc) as rn
        from {{ ref('yf_insider_roster_holders') }}
      ) irh2
    where irh2.rn = 1
  ) irh on spi.ticker = irh.ticker and date(spi.timestamp) = date(irh.day)

  left join (
    select * from (
      select *, date(start_date) as day, row_number() over(partition by date(start_date), ticker order by _sdc_batched_at desc) as rn
        from {{ ref('yf_insider_transactions') }}
      ) it2
    where it2.rn = 1
  ) it on spi.ticker = it.ticker and date(spi.timestamp) = date(it.day)

  left join (
    select * from (
      select *, date(date_reported) as day, row_number() over(partition by date(date_reported), ticker order by _sdc_batched_at desc) as rn
        from {{ ref('yf_institutional_holders') }}
      ) ih2
    where ih2.rn = 1
  ) ih on spi.ticker = ih.ticker and date(spi.timestamp) = date(ih.date_reported)

  left join (
    select * from (
      select *, date(timestamp_extracted) as day, row_number() over(partition by date(timestamp_extracted), ticker order by timestamp_extracted desc) as rn
        from {{ ref('yf_major_holders') }}
      ) mh2
    where mh2.rn = 1
  ) mh on spi.ticker = mh.ticker and date(spi.timestamp) = date(mh.day)

  left join (
    select * from (
      select *, row_number() over(partition by date(date_reported), ticker order by _sdc_batched_at desc) as rn
        from {{ ref('yf_mutualfund_holders') }}
      ) mfh2
    where mfh2.rn = 1
  ) mfh on spi.ticker = mfh.ticker and date(spi.timestamp) = date(mfh.date_reported)

  left join (
    select * from (
      select *, row_number() over(partition by date(timestamp_extracted), ticker order by timestamp_extracted desc) as rn
        from {{ ref('yf_news') }}
      ) news2
    where news2.rn = 1
  ) news on spi.ticker = news.ticker and date(spi.timestamp) = date(news.timestamp_extracted)

  left join {{ ref('yf_quarterly_balance_sheet') }} qbs on spi.ticker = qbs.ticker and date(spi.timestamp) = date(qbs.date)
  left join {{ ref('yf_quarterly_cash_flow') }} qcf on spi.ticker = qcf.ticker and date(spi.timestamp) = date(qcf.date)
  left join {{ ref('yf_quarterly_financials') }} qf on spi.ticker = qf.ticker and date(spi.timestamp) = date(qf.date)
  left join {{ ref('yf_quarterly_income_stmt') }} qis on spi.ticker = qis.ticker and date(spi.timestamp) = date(qis.date)

  left join (
    select * from (
      select *, row_number() over(partition by date(timestamp_extracted), ticker order by timestamp_extracted desc) as rn
        from {{ ref('yf_recommendations') }}
      ) rec2
    where rec2.rn = 1
  ) rec on spi.ticker = rec.ticker and date(spi.timestamp) = date(rec.timestamp_extracted)

  left join (
    select * from (
      select *, row_number() over(partition by date(timestamp), ticker order by _sdc_batched_at desc) as rn
        from {{ ref('yf_shares_full') }}
      ) sf2
    where sf2.rn = 1
  ) sf on spi.ticker = sf.ticker and date(spi.timestamp) = date(sf.timestamp)

  left join (
    select * from (
      select *, row_number() over(partition by date(timestamp), ticker order by _sdc_batched_at desc) as rn
        from {{ ref('yf_splits') }}
      ) sp2
    where sp2.rn = 1
  ) sp on spi.ticker = sp.ticker and date(spi.timestamp) = date(sp.timestamp)

  left join (
    select * from (
      select *, row_number() over(partition by date(grade_date), ticker order by _sdc_batched_at desc) as rn
        from {{ ref('yf_upgrades_downgrades') }}
      ) ud2
    where ud2.rn = 1
  ) ud on spi.ticker = ud.ticker and date(spi.timestamp) = date(ud.grade_date)

)

select * from cte