- credentials
  - NUMERAI_PUBLIC_KEY=<key>
  - NUMERAI_PRIVATE_KEY=<key>
  - MYSQL_USER=<user>
  - MYSQL_PASSWORD=<pw>
  - MYSQL_HOST=<host>
  - GOOGLE_APPLICATION_CREDENTIALS=<loc>
  - ALPHA_VANTAGE_API_KEY=<key>
  - SNOWFLAKE_USER=<user>
  - SNOWFLAKE_WAREHOUSE=<wh>
  - SNOWFLAKE_PASSWORD=<pw>
  - SNOWFLAKE_ACCOUNT=<account>
  - SNOWFLAKE_DATABASE=<db>
  - SNOWFLAKE_SCHEMA=<schema>
  - PKG_CONFIG_PATH=<loc>

- financial_elt:
  - yfinance_elt: true
    yfinance_elt_cron: "{'year': '*', 'month': '*', 'day': '*', 'week': '*', 'day_of_week': '*/3', 'hour': '0', 'minute': '0', 'second': '0'}"
  - feature_creation: false
  - alpha_vantage: false

  - numerai_elt:
    - numerai_tournament: false
    - numerai_signals: false