version: '3'

services:

  financial-elt:
    container_name: financial-elt
    image: financial-elt:latest
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_ENV: dev
    env_file:
      - .env
    environment:
      - DOCKER_DEFAULT_PLATFORM=linux/amd64
    ports:
      - 5000:5000
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 3000M