version: '3'

services:

  financial-elt:
    container_name: financial-elt
    image: financial-elt:latest
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: dev
        GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
    env_file:
      - .env
    environment:
      - DOCKER_DEFAULT_PLATFORM=linux/amd64
    ports:
      - 5000:5000
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: 30000M
