sources:
  - name: tap_yfinance_production
    schema: tap_yfinance_production
    database: financial_elt
    loaded_at_field: _sdc_batched_at
    config:
      freshness:
        warn_after:
          count: 12
          period: hour
        error_after:
          count: 1
          period: day
    tables:
      - name: all_tickers
      - name: prices_1m
      - name: prices_2m
      - name: prices_5m
      - name: prices_1h
      - name: prices_1d
      - name: actions
      - name: analyst_price_targets
      - name: balance_sheet
      - name: calendar
      - name: cash_flow
      - name: dividends
      - name: earnings_dates
      - name: earnings_estimate
      - name: earnings_history
      - name: eps_revisions
      - name: eps_trend
      - name: fast_info
      - name: financials
      - name: growth_estimates
      - name: history_metadata
      - name: info
      - name: income_stmt
      - name: insider_purchases
      - name: insider_roster_holders
      - name: insider_transactions
      - name: institutional_holders
      - name: isin
      - name: major_holders
      - name: mutualfund_holders
      - name: news
      - name: recommendations
      - name: recommendations_summary
      - name: revenue_estimate
      - name: sec_filings
      - name: sec_tickers
      - name: shares_full
      - name: splits
      - name: sustainability
      - name: ttm_cash_flow
      - name: ttm_financials
      - name: ttm_income_stmt
      - name: option_chain
      - name: options
      - name: quarterly_balance_sheet
      - name: quarterly_cash_flow
      - name: quarterly_financials
      - name: quarterly_income_stmt
      - name: upgrades_downgrades
      - name: private_companies_tickers
      - name: etf_tickers
      - name: bonds_tickers
      - name: mutual_fund_tickers
      - name: world_indices_tickers
      - name: sectors
      - name: stock_tickers_pts


  - name: tap_polygon_production
    schema: tap_polygon_production
    database: financial_elt
    loaded_at_field: _sdc_batched_at
    config:
      freshness:
        warn_after:
          count: 12
          period: hour
        error_after:
          count: 1
          period: day
    tables:
      - name: tickers
      - name: ticker_details
      - name: ticker_types
      - name: related_companies
      - name: exchanges
      - name: market_holidays
      - name: market_status
      - name: condition_codes
      - name: ipos
      - name: splits
      - name: dividends
      - name: bars_1_minute
      - name: bars_5_minute
      - name: bars_1_hour
      - name: bars_1_day
      - name: bars_1_week
      - name: bars_1_month
      - name: ticker_events
      - name: financials
      - name: short_interest
      - name: short_volume
      - name: news
      - name: treasury_yields
      - name: daily_market_summary
      - name: daily_ticker_summary
      - name: previous_day_bar
      - name: top_market_movers