name: Lint Python Code

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black pylint isort

    - name: Run flake8
      run: flake8 .

    - name: Run black check
      run: black --check .

      #- name: Run pylint
      #run: pylint ds_core  # or your python package/folder

    - name: Run isort check
      run: isort --check-only .

